#!/usr/bin/env bash
# Digital Product Passport starter launcher (ADR-051 §2.6): a three-member starter chain on the
# packaged Yano cluster launcher, the demo genesis generated by yano-dpp, the public portal, the
# operator gateway, and a demo journey. A PROTOTYPE: not the DPP product of ADR-026.
#
#   DPP_YANO_HOME=/path/to/yano-x-jvm ./dpp.sh up
#   ./dpp.sh seeds | portal | gateway | demo | status | env | stop | clean
#
# The Yano home is an extracted Yano X JVM distribution (or the showcase's yano/ directory):
# it must hold yano.jar, plugins/, config/, and appchain-cluster/cluster.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CHAIN_ID="${DPP_CHAIN_ID:-dpp-starter-chain}"
INSTANCE="${DPP_INSTANCE:-default}"
NODES="${DPP_NODES:-3}"
THRESHOLD="${DPP_THRESHOLD:-2}"
HTTP_BASE="${DPP_HTTP_BASE:-7470}"
SERVER_BASE="${DPP_SERVER_BASE:-9470}"
PORTAL_PORT="${DPP_PORTAL_PORT:-8580}"
GATEWAY_PORT="${DPP_GATEWAY_PORT:-8590}"
DATA_DIR="${DPP_DATA_DIR:-$HOME/.yano-x/dpp}"
DEMO_ACTORS=(dpp-admin-a maker-a logistics-a issuer-a certifier-a auditor-a auditor-b)
DEMO_PRODUCT="${DPP_DEMO_PRODUCT:-gtin:09506000134352}"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
note() { printf '%s\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"; }

usage() {
  cat <<'USAGE'
usage: dpp.sh <command> [--instance <name>] [--nodes <n>] [--threshold <n>]
                        [--http-base <port>] [--server-base <port>] [--portal-port <n>] [--gateway-port <n>]

  up       generate the demo genesis, write the node configuration, start the members
  seeds    write the demo actor seed files (owner-only) and print their paths
  portal   start the public portal (yano-dpp serve) in the background
  gateway  start the operator gateway (yano-dpp gateway) with the demo seeds, in the background
  demo     run the demo journey through the CLI: register, publish, claims, events, certification
  status   cluster, portal, and gateway status
  env      print the node URL, API key, chain id, genesis id, seeds, and service URLs as exports
  stop     stop the portal, the gateway, and the members (data is kept)
  clean    stop and delete the instance

Environment: DPP_YANO_HOME (required), DPP_CLI (yano-dpp launcher, auto-detected), DPP_DATA_DIR
(default ~/.yano-x/dpp). PROTOTYPE: not the DPP product of ADR-026.
USAGE
}

resolve_yano_home() {
  YANO_HOME="${DPP_YANO_HOME:-}"
  if [ -z "$YANO_HOME" ]; then
    local candidate
    for candidate in "$SCRIPT_DIR/../.." "$SCRIPT_DIR/../../../examples/showcase/build/install/yano-showcase/yano"; do
      if [ -f "$candidate/yano.jar" ] && [ -d "$candidate/plugins" ]; then
        YANO_HOME="$(cd "$candidate" && pwd -P)"
        break
      fi
    done
  fi
  [ -n "$YANO_HOME" ] && [ -f "$YANO_HOME/yano.jar" ] && [ -d "$YANO_HOME/plugins" ] \
    && [ -d "$YANO_HOME/config" ] \
    || die "set DPP_YANO_HOME to an extracted Yano X JVM distribution (yano.jar, plugins/, config/)"
  CLUSTER=""
  local launcher
  for launcher in "$YANO_HOME/appchain-cluster/cluster.sh" "$YANO_HOME/examples/appchain-cluster/cluster.sh"; do
    [ -x "$launcher" ] && CLUSTER="$launcher" && break
  done
  [ -n "$CLUSTER" ] || die "the Yano home carries no appchain-cluster/cluster.sh"
}

resolve_cli() {
  CLI="${DPP_CLI:-}"
  if [ -z "$CLI" ]; then
    local candidate
    for candidate in "$SCRIPT_DIR/../../tools/yano-dpp/bin/yano-dpp" \
        "$SCRIPT_DIR/../cli/build/install/yano-dpp/bin/yano-dpp"; do
      if [ -x "$candidate" ]; then CLI="$(cd "$(dirname "$candidate")" && pwd -P)/$(basename "$candidate")"; break; fi
    done
  fi
  [ -n "$CLI" ] && [ -x "$CLI" ] \
    || die "yano-dpp not found; build it (./gradlew :products:dpp:cli:installDist) or set DPP_CLI"
}

instance_root() { printf '%s/%s' "$DATA_DIR" "$INSTANCE"; }
home_dir() { printf '%s/home' "$(instance_root)"; }
node_config_dir() { printf '%s/nodes' "$(instance_root)"; }
cluster_dir() { printf '%s/cluster' "$(instance_root)"; }
seed_dir() { printf '%s/seeds' "$(instance_root)"; }
content_dir() { printf '%s/documents' "$(instance_root)"; }
api_key_file() { printf '%s/api-key' "$(instance_root)"; }
genesis_file() { printf '%s/genesis.properties' "$(instance_root)"; }
marker_file() { printf '%s/dpp.json' "$(instance_root)"; }
token_file() { printf '%s/gateway-token' "$(instance_root)"; }
service_pid() { printf '%s/%s.pid' "$(instance_root)" "$1"; }
service_log() { printf '%s/%s.log' "$(instance_root)" "$1"; }

cluster_env() {
  export YANO_HOME="$(home_dir)" YANO_JAR="$YANO_HOME_DIST/yano.jar"
  export YANO_CLUSTER_DIR="$(cluster_dir)"
  export YANO_CLUSTER_HTTP_BASE="$HTTP_BASE" YANO_CLUSTER_SERVER_BASE="$SERVER_BASE"
  export YANO_CLUSTER_NODE_CONFIG_DIR="$(node_config_dir)"
  export YANO_CLUSTER_PRIVATE_CONFIG_DIR="$(instance_root)/private-config"
  export YANO_CLUSTER_API_KEY="$(cat "$(api_key_file)")"
}

cli_env() {
  export YANO_DPP_URL="http://127.0.0.1:$HTTP_BASE/api/v1"
  export YANO_DPP_CHAIN="$CHAIN_ID"
  export YANO_API_KEY="$(cat "$(api_key_file)")"
  export YANO_DPP_CONTENT_DIR="$(content_dir)"
  export JAVA_OPTS="${JAVA_OPTS:-} --enable-native-access=ALL-UNNAMED"
}

write_home() {
  local home; home="$(home_dir)"
  mkdir -p "$home/config"
  chmod 700 "$(instance_root)" "$home"
  cp -R "$YANO_HOME_DIST/config/." "$home/config/"
  cat > "$home/config/application-appchain.yml" <<YAML
# Generated by dpp.sh: one governed authenticated-map chain carrying the dpp-starter-v1
# profile (ADR-051, a prototype). Membership, signing keys, peers, proposer, threshold, and the
# generated genesis are injected per node by appchain-cluster.
yano:
  plugins:
    allow-list:
      - org.yanoproject.x.stdlib
      - org.yanoproject.x.role-workflow
      - org.yanoproject.x.composite
  app-chain:
    chains[0]:
      chain-id: "$CHAIN_ID"
      state-machine: "authenticated-map"
      membership:
        mode: "governed"
      block:
        interval-ms: "1000"
YAML
  [ -e "$home/plugins" ] || ln -s "$YANO_HOME_DIST/plugins" "$home/plugins"
}

write_node_configs() {
  local dir i file
  dir="$(node_config_dir)"
  mkdir -p "$dir"; chmod 700 "$dir"
  find "$dir" -maxdepth 1 -type f -name 'node*.properties' -delete
  for ((i=0;i<NODES;i++)); do
    file="$dir/node$i.properties"
    {
      printf 'config_ordinal=275\n'
      printf 'yano.plugins.enabled=true\n'
      printf 'yano.plugins.directory=%s/plugins\n' "$YANO_HOME_DIST"
      # The devnet profile projects L1 history into ./history under the shared home; a starter
      # member needs no L1 history, and members must not share one archive.
      printf 'yano.history.projection.enabled=false\n'
      cat "$(genesis_file)"
    } > "$file"
    chmod 600 "$file"
  done
}

write_seeds() {
  local dir actor
  dir="$(seed_dir)"
  mkdir -p "$dir"; chmod 700 "$dir"
  for actor in "${DEMO_ACTORS[@]}"; do
    # Demo-only deterministic seed shared with DppGenesis.demoActorSeed.
    python3 - "$actor" > "$dir/$actor.seed" <<'PY'
import hashlib, sys
print(hashlib.sha256(("yano-dpp-starter-demo-actor:" + sys.argv[1]).encode()).hexdigest())
PY
    chmod 600 "$dir/$actor.seed"
  done
}

genesis_id() {
  grep 'state.genesis-id=' "$(genesis_file)" | cut -d= -f2
}

service_running() {
  [ -f "$(service_pid "$1")" ] && kill -0 "$(cat "$(service_pid "$1")")" 2>/dev/null
}

start_service() {
  local name="$1"; shift
  if service_running "$name"; then die "$name is already running (pid $(cat "$(service_pid "$name")"))"; fi
  nohup "$CLI" "$@" > "$(service_log "$name")" 2>&1 &
  echo $! > "$(service_pid "$name")"
}

await_health() {
  local url="$1" name="$2" i
  for i in $(seq 1 30); do
    if curl -fsS "$url/healthz" >/dev/null 2>&1; then return 0; fi
    sleep 1
  done
  tail -20 "$(service_log "$name")" >&2
  die "$name did not come up; see $(service_log "$name")"
}

stop_service() {
  local name="$1"
  if service_running "$name"; then kill "$(cat "$(service_pid "$name")")" && note "stopped $name (pid $(cat "$(service_pid "$name")"))"; fi
  rm -f "$(service_pid "$name")"
}

cmd_up() {
  need java; need python3; need curl
  resolve_yano_home; YANO_HOME_DIST="$YANO_HOME"; resolve_cli
  [ ! -f "$(marker_file)" ] || die "instance '$INSTANCE' already exists; run stop/clean or pick another --instance"
  mkdir -p "$(instance_root)"; chmod 700 "$(instance_root)"
  write_home
  (umask 077; python3 -c 'import secrets; print(secrets.token_hex(32))' > "$(api_key_file)")
  local members
  members="$(YANO_HOME="$(home_dir)" YANO_JAR="$YANO_HOME_DIST/yano.jar" "$CLUSTER" keys "$NODES" \
    | awk 'NR > 1 {print $3}' | paste -sd, -)"
  [ -n "$members" ] || die "could not derive member keys from the cluster launcher"
  (umask 077; "$CLI" genesis --demo --chain "$CHAIN_ID" --members "$members" --threshold "$THRESHOLD" \
    --chain-index 0 --output "$(genesis_file)" >/dev/null)
  grep -q 'state.genesis-id=' "$(genesis_file)" || die "genesis generation produced no properties"
  # Members file for offline verification (yano-dpp verify --members), ADR-047 §7 format.
  python3 - "$(instance_root)/members.json" "$CHAIN_ID" "$THRESHOLD" "$members" <<'PY'
import json, sys
path, chain, threshold, members = sys.argv[1:]
with open(path, "w") as handle:
    json.dump({"chainId": chain, "memberKeysHex": members.split(","), "threshold": int(threshold)},
              handle, indent=2)
    handle.write("\n")
PY
  write_node_configs
  write_seeds
  mkdir -p "$(content_dir)"; chmod 700 "$(content_dir)"
  python3 - "$(marker_file)" "$INSTANCE" "$CHAIN_ID" "$NODES" "$THRESHOLD" "$HTTP_BASE" "$SERVER_BASE" \
      "$PORTAL_PORT" "$GATEWAY_PORT" "$(genesis_id)" "$YANO_HOME_DIST" <<'PY'
import json, os, sys
(path, instance, chain, nodes, threshold, http_base, server_base, portal_port, gateway_port,
 genesis_id, home) = sys.argv[1:]
doc = {"schemaVersion": 1, "instance": instance, "chainId": chain, "nodes": int(nodes),
       "threshold": int(threshold), "httpBase": int(http_base), "serverBase": int(server_base),
       "portalPort": int(portal_port), "gatewayPort": int(gateway_port),
       "mapGenesisId": genesis_id, "yanoHome": home}
fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
with os.fdopen(fd, "w") as handle:
    json.dump(doc, handle, indent=2)
    handle.write("\n")
PY
  cluster_env
  "$CLUSTER" start "$NODES"
  note ""
  note "DPP starter '$INSTANCE' is starting: chain $CHAIN_ID, $NODES members, threshold $THRESHOLD (PROTOTYPE)"
  note "  node 0:        http://127.0.0.1:$HTTP_BASE/api/v1"
  note "  API key file:  $(api_key_file)"
  note "  map genesis:   $(genesis_id)"
  note "  members file:  $(instance_root)/members.json"
  note "  seeds:         $(seed_dir)/<actor>.seed  (${DEMO_ACTORS[*]})"
  note "  documents:     $(content_dir)"
  note "Next: './dpp.sh demo' populates a passport; './dpp.sh portal' and './dpp.sh gateway' start the services."
}

adopt() {
  [ -f "$(marker_file)" ] || die "instance '$INSTANCE' does not exist; run up first"
  python3 - "$(marker_file)" <<'PY' > "$(instance_root)/.env.tmp"
import json, sys
doc = json.load(open(sys.argv[1]))
for key, name in (("chainId", "CHAIN_ID"), ("nodes", "NODES"), ("threshold", "THRESHOLD"),
                  ("httpBase", "HTTP_BASE"), ("serverBase", "SERVER_BASE"), ("portalPort", "PORTAL_PORT"),
                  ("gatewayPort", "GATEWAY_PORT"), ("yanoHome", "YANO_HOME_DIST")):
    print("%s=%s" % (name, doc[key]))
PY
  # shellcheck disable=SC1090
  . "$(instance_root)/.env.tmp"
  rm -f "$(instance_root)/.env.tmp"
  YANO_HOME="$YANO_HOME_DIST"; resolve_yano_home; YANO_HOME_DIST="$YANO_HOME"
  resolve_cli
}

cmd_portal() {
  adopt; cli_env
  start_service portal serve --bind 127.0.0.1 --port "$PORTAL_PORT" --content-dir "$(content_dir)"
  await_health "http://127.0.0.1:$PORTAL_PORT" portal
  note "portal on http://127.0.0.1:$PORTAL_PORT (log $(service_log portal))"
}

cmd_gateway() {
  adopt; cli_env
  write_seeds
  start_service gateway gateway --bind 127.0.0.1 --port "$GATEWAY_PORT" --content-dir "$(content_dir)" \
    --seeds "$(seed_dir)" --token-file "$(token_file)" --genesis-id "$(genesis_id)"
  await_health "http://127.0.0.1:$GATEWAY_PORT" gateway
  note "gateway on http://127.0.0.1:$GATEWAY_PORT signing for ${DEMO_ACTORS[*]} (log $(service_log gateway))"
  note "  token: $(cat "$(token_file)")"
}

cmd_demo() {
  adopt; cli_env
  write_seeds
  local seeds tmp doc
  seeds="$(seed_dir)"
  tmp="$(mktemp -d "$(instance_root)/demo.XXXXXX")"
  doc="$tmp/passport-v1.json"
  printf '{"passport":"battery","product":"%s","version":1,"chemistry":"LFP","capacityWh":5120}\n' "$DEMO_PRODUCT" > "$doc"
  printf '{"inspection":"visual and electrical","result":"pass"}\n' > "$tmp/inspection.json"
  local first=()
  if [ "$("$CLI" passport --product "$DEMO_PRODUCT" --json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["passport"]["status"])' 2>/dev/null || echo ABSENT)" != "ABSENT" ]; then
    die "product $DEMO_PRODUCT already has a passport on this instance; pick another with DPP_DEMO_PRODUCT"
  fi
  # The first write on a fresh chain signs from the generated genesis id.
  first=(--genesis-id "$(genesis_id)")
  note "== maker-a registers $DEMO_PRODUCT"
  "$CLI" register --product "$DEMO_PRODUCT" --manufacturer-org acme-manufacturing --profile battery-passport-demo-v1 \
    --actor maker-a --seed-file "$seeds/maker-a.seed" "${first[@]}"
  note "== maker-a publishes version 1 and activates the passport"
  "$CLI" publish-version --product "$DEMO_PRODUCT" --version 1 --document "$doc" \
    --reference "https://acme.example/passports/$DEMO_PRODUCT/v1.json" --actor maker-a --seed-file "$seeds/maker-a.seed"
  "$CLI" set-status --product "$DEMO_PRODUCT" --status ACTIVE --actor maker-a --seed-file "$seeds/maker-a.seed"
  note "== issuer-a attaches a public and a committed claim"
  "$CLI" claim --product "$DEMO_PRODUCT" --type recycled-content --id rc-1 --text "42 %" \
    --actor issuer-a --seed-file "$seeds/issuer-a.seed"
  "$CLI" claim --product "$DEMO_PRODUCT" --type carbon-footprint --id cf-1 --text "12.5 kgCO2e" --committed \
    --disclosure-output "$(instance_root)/disclosure-cf-1.json" --actor issuer-a --seed-file "$seeds/issuer-a.seed"
  note "== lifecycle events"
  "$CLI" event --product "$DEMO_PRODUCT" --type MANUFACTURED --id e-1 --location "Plant 7" \
    --actor maker-a --seed-file "$seeds/maker-a.seed"
  "$CLI" event --product "$DEMO_PRODUCT" --type SHIPPED --id e-2 --location Rotterdam --note "container MSKU1" \
    --actor logistics-a --seed-file "$seeds/logistics-a.seed"
  "$CLI" event --product "$DEMO_PRODUCT" --type RECEIVED --id e-3 --location Hamburg \
    --actor logistics-a --seed-file "$seeds/logistics-a.seed"
  note "== certification round: certifier-a proposes, auditor-a and auditor-b approve, apply"
  "$CLI" certify propose --product "$DEMO_PRODUCT" --certificate cert-eco-1 --type EU-Ecodesign \
    --evidence "$tmp/inspection.json" --output "$tmp/request.json" --actor certifier-a --seed-file "$seeds/certifier-a.seed"
  "$CLI" certify approve --request "$tmp/request.json" --actor auditor-a --seed-file "$seeds/auditor-a.seed"
  "$CLI" certify approve --request "$tmp/request.json" --actor auditor-b --seed-file "$seeds/auditor-b.seed"
  "$CLI" certify apply --request "$tmp/request.json"
  note "== the passport, verified under the members file"
  "$CLI" passport --product "$DEMO_PRODUCT" --members "$(instance_root)/members.json" \
    --output "$(instance_root)/passport-demo.json" || true
  note "Passport bundle: $(instance_root)/passport-demo.json; disclosure: $(instance_root)/disclosure-cf-1.json"
  rm -rf -- "$tmp"
}

cmd_env() {
  adopt
  printf 'export YANO_DPP_URL=%q\n' "http://127.0.0.1:$HTTP_BASE/api/v1"
  printf 'export YANO_DPP_CHAIN=%q\n' "$CHAIN_ID"
  printf 'export YANO_API_KEY=%q\n' "$(cat "$(api_key_file)")"
  printf 'export YANO_DPP_GENESIS_ID=%q\n' "$(genesis_id)"
  printf 'export YANO_DPP_SEEDS=%q\n' "$(seed_dir)"
  printf 'export YANO_DPP_MEMBERS=%q\n' "$(instance_root)/members.json"
  printf 'export YANO_DPP_CONTENT_DIR=%q\n' "$(content_dir)"
  printf 'export DPP_PORTAL_URL=%q\n' "http://127.0.0.1:$PORTAL_PORT"
  printf 'export DPP_GATEWAY_URL=%q\n' "http://127.0.0.1:$GATEWAY_PORT"
  [ -f "$(token_file)" ] && printf 'export DPP_GATEWAY_TOKEN=%q\n' "$(cat "$(token_file)")"
}

cmd_status() {
  adopt; cluster_env
  "$CLUSTER" status || true
  local name
  for name in portal gateway; do
    if service_running "$name"; then note "$name: running (pid $(cat "$(service_pid "$name")"))"; else note "$name: stopped"; fi
  done
}

main() {
  local command="${1:-}"; shift || true
  while [ $# -gt 0 ]; do
    case "$1" in
      --instance) INSTANCE="${2:?}"; shift 2;;
      --nodes) NODES="${2:?}"; shift 2;;
      --threshold) THRESHOLD="${2:?}"; shift 2;;
      --http-base) HTTP_BASE="${2:?}"; shift 2;;
      --server-base) SERVER_BASE="${2:?}"; shift 2;;
      --portal-port) PORTAL_PORT="${2:?}"; shift 2;;
      --gateway-port) GATEWAY_PORT="${2:?}"; shift 2;;
      -h|--help) usage; exit 0;;
      *) die "unknown option: $1";;
    esac
  done
  [[ "$INSTANCE" =~ ^[A-Za-z0-9._-]{1,64}$ ]] || die "invalid instance name"
  [[ "$NODES" =~ ^[0-9]+$ ]] && [ "$NODES" -ge 1 ] && [ "$NODES" -le 32 ] || die "--nodes must be 1-32"
  [[ "$THRESHOLD" =~ ^[0-9]+$ ]] && [ "$THRESHOLD" -ge 1 ] && [ "$THRESHOLD" -le "$NODES" ] \
    || die "--threshold must be between 1 and the node count"
  case "$command" in
    up) cmd_up;;
    seeds) adopt; write_seeds; ls -1 "$(seed_dir)";;
    portal) cmd_portal;;
    gateway) cmd_gateway;;
    demo) cmd_demo;;
    status) cmd_status;;
    env) cmd_env;;
    stop) adopt; stop_service portal; stop_service gateway; cluster_env; "$CLUSTER" stop;;
    clean) adopt; stop_service portal; stop_service gateway; cluster_env; "$CLUSTER" clean || true; rm -rf -- "$(instance_root)"; note "removed $(instance_root)";;
    ""|help|-h|--help) usage;;
    *) die "unknown command: $command";;
  esac
}

main "$@"
