#!/usr/bin/env bash
# Data attestation feed starter launcher (ADR-052 §2.6): a three-member starter chain on the
# packaged Yano cluster launcher, the demo genesis generated by yano-feed, the public portal, the
# signing gateway, and a demo journey. EXPERIMENTAL: not the oracle pipeline of ADR app-layer/012;
# aggregates are recomputed by verifiers, nothing is published to Cardano.
#
#   FEED_YANO_HOME=/path/to/yano-x-jvm ./feed.sh up
#   ./feed.sh seeds | portal | gateway | demo | status | env | stop | clean
#
# The Yano home is an extracted Yano X JVM distribution (or the showcase's yano/ directory):
# it must hold yano.jar, plugins/, config/, and appchain-cluster/cluster.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CHAIN_ID="${FEED_CHAIN_ID:-attestation-feed-chain}"
INSTANCE="${FEED_INSTANCE:-default}"
NODES="${FEED_NODES:-3}"
THRESHOLD="${FEED_THRESHOLD:-2}"
HTTP_BASE="${FEED_HTTP_BASE:-7570}"
SERVER_BASE="${FEED_SERVER_BASE:-9570}"
PORTAL_PORT="${FEED_PORTAL_PORT:-8680}"
GATEWAY_PORT="${FEED_GATEWAY_PORT:-8690}"
DATA_DIR="${FEED_DATA_DIR:-$HOME/.yano-x/attestation-feed}"
DEMO_ACTORS=(feed-admin-a source-alpha source-beta source-gamma ops-a publisher-a publisher-c publisher-b)
DEMO_FEED="${FEED_DEMO_FEED:-coldstore-7}"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
note() { printf '%s\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"; }

usage() {
  cat <<'USAGE'
usage: feed.sh <command> [--instance <name>] [--nodes <n>] [--threshold <n>]
                         [--http-base <port>] [--server-base <port>] [--portal-port <n>] [--gateway-port <n>]

  up       generate the demo genesis, write the node configuration, start the members
  seeds    write the demo actor seed files (owner-only) and print their paths
  portal   start the public portal (yano-feed serve) in the background
  gateway  start the signing gateway (yano-feed gateway) with the demo seeds, in the background
  demo     run the demo journey through the CLI: a feed, three simulated sources with one outlier,
           a same-organization approval refused on apply, the round closed, a NO_QUORUM round
  status   cluster, portal, and gateway status
  env      print the node URL, API key, chain id, genesis id, seeds, and service URLs as exports
  stop     stop the portal, the gateway, and the members (data is kept)
  clean    stop and delete the instance

Environment: FEED_YANO_HOME (required), FEED_CLI (yano-feed launcher, auto-detected), FEED_DATA_DIR
(default ~/.yano-x/attestation-feed). EXPERIMENTAL: not the oracle pipeline of ADR app-layer/012.
USAGE
}

resolve_yano_home() {
  YANO_HOME="${FEED_YANO_HOME:-}"
  if [ -z "$YANO_HOME" ]; then
    local candidate
    for candidate in "$SCRIPT_DIR/../.." "$SCRIPT_DIR/../../../examples/showcase/build/install/yano-showcase/yano"; do
      if [ -f "$candidate/yano.jar" ] && [ -d "$candidate/plugins" ]; then
        YANO_HOME="$(cd "$candidate" && pwd -P)"
        break
      fi
    done
  fi
  [ -n "$YANO_HOME" ] && [ -f "$YANO_HOME/yano.jar" ] && [ -d "$YANO_HOME/plugins" ] \
    && [ -d "$YANO_HOME/config" ] \
    || die "set FEED_YANO_HOME to an extracted Yano X JVM distribution (yano.jar, plugins/, config/)"
  CLUSTER=""
  local launcher
  for launcher in "$YANO_HOME/appchain-cluster/cluster.sh" "$YANO_HOME/examples/appchain-cluster/cluster.sh"; do
    [ -x "$launcher" ] && CLUSTER="$launcher" && break
  done
  [ -n "$CLUSTER" ] || die "the Yano home carries no appchain-cluster/cluster.sh"
}

resolve_cli() {
  CLI="${FEED_CLI:-}"
  if [ -z "$CLI" ]; then
    local candidate
    for candidate in "$SCRIPT_DIR/../../tools/yano-feed/bin/yano-feed" \
        "$SCRIPT_DIR/../cli/build/install/yano-feed/bin/yano-feed"; do
      if [ -x "$candidate" ]; then CLI="$(cd "$(dirname "$candidate")" && pwd -P)/$(basename "$candidate")"; break; fi
    done
  fi
  [ -n "$CLI" ] && [ -x "$CLI" ] \
    || die "yano-feed not found; build it (./gradlew :products:attestation-feed:cli:installDist) or set FEED_CLI"
}

instance_root() { printf '%s/%s' "$DATA_DIR" "$INSTANCE"; }
home_dir() { printf '%s/home' "$(instance_root)"; }
node_config_dir() { printf '%s/nodes' "$(instance_root)"; }
cluster_dir() { printf '%s/cluster' "$(instance_root)"; }
seed_dir() { printf '%s/seeds' "$(instance_root)"; }
api_key_file() { printf '%s/api-key' "$(instance_root)"; }
genesis_file() { printf '%s/genesis.properties' "$(instance_root)"; }
marker_file() { printf '%s/feed.json' "$(instance_root)"; }
token_file() { printf '%s/gateway-token' "$(instance_root)"; }
service_pid() { printf '%s/%s.pid' "$(instance_root)" "$1"; }
service_log() { printf '%s/%s.log' "$(instance_root)" "$1"; }

cluster_env() {
  export YANO_HOME="$(home_dir)" YANO_JAR="$YANO_HOME_DIST/yano.jar"
  export YANO_CLUSTER_DIR="$(cluster_dir)"
  export YANO_CLUSTER_HTTP_BASE="$HTTP_BASE" YANO_CLUSTER_SERVER_BASE="$SERVER_BASE"
  export YANO_CLUSTER_NODE_CONFIG_DIR="$(node_config_dir)"
  export YANO_CLUSTER_PRIVATE_CONFIG_DIR="$(instance_root)/private-config"
  export YANO_CLUSTER_API_KEY="$(cat "$(api_key_file)")"
}

cli_env() {
  export YANO_FEED_URL="http://127.0.0.1:$HTTP_BASE/api/v1"
  export YANO_FEED_CHAIN="$CHAIN_ID"
  export YANO_API_KEY="$(cat "$(api_key_file)")"
  export JAVA_OPTS="${JAVA_OPTS:-} --enable-native-access=ALL-UNNAMED"
}

write_home() {
  local home; home="$(home_dir)"
  mkdir -p "$home/config"
  chmod 700 "$(instance_root)" "$home"
  cp -R "$YANO_HOME_DIST/config/." "$home/config/"
  cat > "$home/config/application-appchain.yml" <<YAML
# Generated by feed.sh: one governed authenticated-map chain carrying the
# attestation-feed-starter-v1 profile (ADR-052, experimental). Membership, signing keys, peers,
# proposer, threshold, and the generated genesis are injected per node by appchain-cluster.
yano:
  plugins:
    allow-list:
      - com.bloxbean.cardano.yano.appchain.stdlib
      - com.bloxbean.cardano.yano.appchain.role-workflow
      - com.bloxbean.cardano.yano.appchain.composite
  app-chain:
    chains[0]:
      chain-id: "$CHAIN_ID"
      state-machine: "authenticated-map"
      membership:
        mode: "governed"
      block:
        interval-ms: "1000"
YAML
  [ -e "$home/plugins" ] || ln -s "$YANO_HOME_DIST/plugins" "$home/plugins"
}

write_node_configs() {
  local dir i file
  dir="$(node_config_dir)"
  mkdir -p "$dir"; chmod 700 "$dir"
  find "$dir" -maxdepth 1 -type f -name 'node*.properties' -delete
  for ((i=0;i<NODES;i++)); do
    file="$dir/node$i.properties"
    {
      printf 'config_ordinal=275\n'
      printf 'yano.plugins.enabled=true\n'
      printf 'yano.plugins.directory=%s/plugins\n' "$YANO_HOME_DIST"
      # The devnet profile projects L1 history into ./history under the shared home; a starter
      # member needs no L1 history, and members must not share one archive.
      printf 'yano.history.projection.enabled=false\n'
      cat "$(genesis_file)"
    } > "$file"
    chmod 600 "$file"
  done
}

write_seeds() {
  local dir actor
  dir="$(seed_dir)"
  mkdir -p "$dir"; chmod 700 "$dir"
  for actor in "${DEMO_ACTORS[@]}"; do
    # Demo-only deterministic seed shared with FeedGenesis.demoActorSeed.
    python3 - "$actor" > "$dir/$actor.seed" <<'PY'
import hashlib, sys
print(hashlib.sha256(("yano-attestation-feed-demo-actor:" + sys.argv[1]).encode()).hexdigest())
PY
    chmod 600 "$dir/$actor.seed"
  done
}

genesis_id() {
  grep 'state.genesis-id=' "$(genesis_file)" | cut -d= -f2
}

service_running() {
  [ -f "$(service_pid "$1")" ] && kill -0 "$(cat "$(service_pid "$1")")" 2>/dev/null
}

start_service() {
  local name="$1"; shift
  if service_running "$name"; then die "$name is already running (pid $(cat "$(service_pid "$name")"))"; fi
  nohup "$CLI" "$@" > "$(service_log "$name")" 2>&1 &
  echo $! > "$(service_pid "$name")"
}

await_health() {
  local url="$1" name="$2" i
  for i in $(seq 1 30); do
    if curl -fsS "$url/healthz" >/dev/null 2>&1; then return 0; fi
    sleep 1
  done
  tail -20 "$(service_log "$name")" >&2
  die "$name did not come up; see $(service_log "$name")"
}

stop_service() {
  local name="$1"
  if service_running "$name"; then kill "$(cat "$(service_pid "$name")")" && note "stopped $name (pid $(cat "$(service_pid "$name")"))"; fi
  rm -f "$(service_pid "$name")"
}

cmd_up() {
  need java; need python3; need curl
  resolve_yano_home; YANO_HOME_DIST="$YANO_HOME"; resolve_cli
  [ ! -f "$(marker_file)" ] || die "instance '$INSTANCE' already exists; run stop/clean or pick another --instance"
  mkdir -p "$(instance_root)"; chmod 700 "$(instance_root)"
  write_home
  (umask 077; python3 -c 'import secrets; print(secrets.token_hex(32))' > "$(api_key_file)")
  local members
  members="$(YANO_HOME="$(home_dir)" YANO_JAR="$YANO_HOME_DIST/yano.jar" "$CLUSTER" keys "$NODES" \
    | awk 'NR > 1 {print $3}' | paste -sd, -)"
  [ -n "$members" ] || die "could not derive member keys from the cluster launcher"
  (umask 077; "$CLI" genesis --demo --chain "$CHAIN_ID" --members "$members" --threshold "$THRESHOLD" \
    --chain-index 0 --output "$(genesis_file)" >/dev/null)
  grep -q 'state.genesis-id=' "$(genesis_file)" || die "genesis generation produced no properties"
  # Members file for offline verification (yano-feed verify --members), ADR-047 §7 format.
  python3 - "$(instance_root)/members.json" "$CHAIN_ID" "$THRESHOLD" "$members" <<'PY'
import json, sys
path, chain, threshold, members = sys.argv[1:]
with open(path, "w") as handle:
    json.dump({"chainId": chain, "memberKeysHex": members.split(","), "threshold": int(threshold)},
              handle, indent=2)
    handle.write("\n")
PY
  write_node_configs
  write_seeds
  python3 - "$(marker_file)" "$INSTANCE" "$CHAIN_ID" "$NODES" "$THRESHOLD" "$HTTP_BASE" "$SERVER_BASE" \
      "$PORTAL_PORT" "$GATEWAY_PORT" "$(genesis_id)" "$YANO_HOME_DIST" <<'PY'
import json, os, sys
(path, instance, chain, nodes, threshold, http_base, server_base, portal_port, gateway_port,
 genesis_id, home) = sys.argv[1:]
doc = {"schemaVersion": 1, "instance": instance, "chainId": chain, "nodes": int(nodes),
       "threshold": int(threshold), "httpBase": int(http_base), "serverBase": int(server_base),
       "portalPort": int(portal_port), "gatewayPort": int(gateway_port),
       "mapGenesisId": genesis_id, "yanoHome": home}
fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
with os.fdopen(fd, "w") as handle:
    json.dump(doc, handle, indent=2)
    handle.write("\n")
PY
  cluster_env
  "$CLUSTER" start "$NODES"
  note ""
  note "Attestation feed starter '$INSTANCE' is starting: chain $CHAIN_ID, $NODES members, threshold $THRESHOLD (EXPERIMENTAL)"
  note "  node 0:        http://127.0.0.1:$HTTP_BASE/api/v1"
  note "  API key file:  $(api_key_file)"
  note "  map genesis:   $(genesis_id)"
  note "  members file:  $(instance_root)/members.json"
  note "  seeds:         $(seed_dir)/<actor>.seed  (${DEMO_ACTORS[*]})"
  note "Next: './feed.sh demo' defines and closes a round; './feed.sh portal' and './feed.sh gateway' start the services."
}

adopt() {
  [ -f "$(marker_file)" ] || die "instance '$INSTANCE' does not exist; run up first"
  python3 - "$(marker_file)" <<'PY' > "$(instance_root)/.env.tmp"
import json, sys
doc = json.load(open(sys.argv[1]))
for key, name in (("chainId", "CHAIN_ID"), ("nodes", "NODES"), ("threshold", "THRESHOLD"),
                  ("httpBase", "HTTP_BASE"), ("serverBase", "SERVER_BASE"), ("portalPort", "PORTAL_PORT"),
                  ("gatewayPort", "GATEWAY_PORT"), ("yanoHome", "YANO_HOME_DIST")):
    print("%s=%s" % (name, doc[key]))
PY
  # shellcheck disable=SC1090
  . "$(instance_root)/.env.tmp"
  rm -f "$(instance_root)/.env.tmp"
  YANO_HOME="$YANO_HOME_DIST"; resolve_yano_home; YANO_HOME_DIST="$YANO_HOME"
  resolve_cli
}

cmd_portal() {
  adopt; cli_env
  start_service portal serve --bind 127.0.0.1 --port "$PORTAL_PORT"
  await_health "http://127.0.0.1:$PORTAL_PORT" portal
  note "portal on http://127.0.0.1:$PORTAL_PORT (log $(service_log portal))"
}

cmd_gateway() {
  adopt; cli_env
  write_seeds
  start_service gateway gateway --bind 127.0.0.1 --port "$GATEWAY_PORT" \
    --seeds "$(seed_dir)" --token-file "$(token_file)" --genesis-id "$(genesis_id)"
  await_health "http://127.0.0.1:$GATEWAY_PORT" gateway
  note "gateway on http://127.0.0.1:$GATEWAY_PORT signing for ${DEMO_ACTORS[*]} (log $(service_log gateway))"
  note "  token: $(cat "$(token_file)")"
}

# The demo feed: a cold-store temperature in hundredths of a degree, one-minute rounds starting at
# the current minute, three sources, quorum two, outliers beyond 2 % or 0.50 degC.
write_demo_spec() {
  local epoch; epoch="$(( $(date +%s) / 60 * 60 - 600 ))"
  cat > "$1" <<JSON
{
  "description": "Cold store 7 air temperature",
  "unit": "degC",
  "scale": 2,
  "epochStart": $epoch,
  "roundSeconds": 60,
  "sources": ["source-alpha", "source-beta", "source-gamma"],
  "minimumSources": 2,
  "maximumDeviationPpm": 20000,
  "maximumDeviationAbsolute": 50,
  "minimumValue": -4000,
  "maximumValue": 1000
}
JSON
}

cmd_demo() {
  adopt; cli_env
  write_seeds
  local seeds tmp round next
  seeds="$(seed_dir)"
  tmp="$(mktemp -d "$(instance_root)/demo.XXXXXX")"
  if "$CLI" feed get --feed "$DEMO_FEED" >/dev/null 2>&1; then
    die "feed $DEMO_FEED already exists on this instance; pick another with FEED_DEMO_FEED"
  fi
  write_demo_spec "$tmp/feed.json"
  note "== feed-admin-a defines $DEMO_FEED (the first write signs from the generated genesis id)"
  "$CLI" feed create --feed "$DEMO_FEED" --spec "$tmp/feed.json" --actor feed-admin-a \
    --seed-file "$seeds/feed-admin-a.seed" --genesis-id "$(genesis_id)"
  round="$(( ( $(date +%s) - $(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["epochStart"])' "$tmp/feed.json") ) / 60 ))"
  note "== three simulated sources report round $round; source-gamma is an outlier"
  "$CLI" simulate --feed "$DEMO_FEED" --round "$round" --sources source-alpha,source-beta,source-gamma \
    --seeds "$seeds" --base -1825 --outlier source-gamma
  note "== ops-a proposes the round close"
  "$CLI" round propose --feed "$DEMO_FEED" --round "$round" --output "$tmp/request.json" \
    --actor ops-a --seed-file "$seeds/ops-a.seed"
  note "== publisher-a and publisher-c (the same organization) approve; apply is refused"
  "$CLI" round approve --request "$tmp/request.json" --actor publisher-a --seed-file "$seeds/publisher-a.seed"
  "$CLI" round approve --request "$tmp/request.json" --actor publisher-c --seed-file "$seeds/publisher-c.seed"
  if "$CLI" round apply --request "$tmp/request.json"; then
    die "apply should have been refused with two approvals from one organization"
  fi
  note "== publisher-b (another organization) approves; apply succeeds"
  "$CLI" round approve --request "$tmp/request.json" --actor publisher-b --seed-file "$seeds/publisher-b.seed"
  "$CLI" round apply --request "$tmp/request.json"
  note "== the closed round, verified under the members file (exit 5), exported"
  "$CLI" round get --feed "$DEMO_FEED" --round "$round" --members "$(instance_root)/members.json" \
    --output "$(instance_root)/round-demo.json" || true
  next=$((round + 1))
  note "== round $next: one source only, recorded as NO_QUORUM"
  "$CLI" simulate --feed "$DEMO_FEED" --round "$next" --sources source-alpha --seeds "$seeds" --base -1830 \
    --observed-at "$(( $(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["epochStart"])' "$tmp/feed.json") + next * 60 + 5 ))"
  "$CLI" round propose --feed "$DEMO_FEED" --round "$next" --output "$tmp/request-next.json" \
    --actor ops-a --seed-file "$seeds/ops-a.seed"
  "$CLI" round approve --request "$tmp/request-next.json" --actor publisher-a --seed-file "$seeds/publisher-a.seed"
  "$CLI" round approve --request "$tmp/request-next.json" --actor publisher-b --seed-file "$seeds/publisher-b.seed"
  "$CLI" round apply --request "$tmp/request-next.json"
  "$CLI" round get --feed "$DEMO_FEED" --round "$next" --members "$(instance_root)/members.json" || true
  note "Round bundle: $(instance_root)/round-demo.json (round $round of $DEMO_FEED)"
  rm -rf -- "$tmp"
}

cmd_env() {
  adopt
  printf 'export YANO_FEED_URL=%q\n' "http://127.0.0.1:$HTTP_BASE/api/v1"
  printf 'export YANO_FEED_CHAIN=%q\n' "$CHAIN_ID"
  printf 'export YANO_API_KEY=%q\n' "$(cat "$(api_key_file)")"
  printf 'export YANO_FEED_GENESIS_ID=%q\n' "$(genesis_id)"
  printf 'export YANO_FEED_SEEDS=%q\n' "$(seed_dir)"
  printf 'export YANO_FEED_MEMBERS=%q\n' "$(instance_root)/members.json"
  printf 'export FEED_PORTAL_URL=%q\n' "http://127.0.0.1:$PORTAL_PORT"
  printf 'export FEED_GATEWAY_URL=%q\n' "http://127.0.0.1:$GATEWAY_PORT"
  [ -f "$(token_file)" ] && printf 'export FEED_GATEWAY_TOKEN=%q\n' "$(cat "$(token_file)")"
}

cmd_status() {
  adopt; cluster_env
  "$CLUSTER" status || true
  local name
  for name in portal gateway; do
    if service_running "$name"; then note "$name: running (pid $(cat "$(service_pid "$name")"))"; else note "$name: stopped"; fi
  done
}

main() {
  local command="${1:-}"; shift || true
  while [ $# -gt 0 ]; do
    case "$1" in
      --instance) INSTANCE="${2:?}"; shift 2;;
      --nodes) NODES="${2:?}"; shift 2;;
      --threshold) THRESHOLD="${2:?}"; shift 2;;
      --http-base) HTTP_BASE="${2:?}"; shift 2;;
      --server-base) SERVER_BASE="${2:?}"; shift 2;;
      --portal-port) PORTAL_PORT="${2:?}"; shift 2;;
      --gateway-port) GATEWAY_PORT="${2:?}"; shift 2;;
      -h|--help) usage; exit 0;;
      *) die "unknown option: $1";;
    esac
  done
  [[ "$INSTANCE" =~ ^[A-Za-z0-9._-]{1,64}$ ]] || die "invalid instance name"
  [[ "$NODES" =~ ^[0-9]+$ ]] && [ "$NODES" -ge 1 ] && [ "$NODES" -le 32 ] || die "--nodes must be 1-32"
  [[ "$THRESHOLD" =~ ^[0-9]+$ ]] && [ "$THRESHOLD" -ge 1 ] && [ "$THRESHOLD" -le "$NODES" ] \
    || die "--threshold must be between 1 and the node count"
  case "$command" in
    up) cmd_up;;
    seeds) adopt; write_seeds; ls -1 "$(seed_dir)";;
    portal) cmd_portal;;
    gateway) cmd_gateway;;
    demo) cmd_demo;;
    status) cmd_status;;
    env) cmd_env;;
    stop) adopt; stop_service portal; stop_service gateway; cluster_env; "$CLUSTER" stop;;
    clean) adopt; stop_service portal; stop_service gateway; cluster_env; "$CLUSTER" clean || true; rm -rf -- "$(instance_root)"; note "removed $(instance_root)";;
    ""|help|-h|--help) usage;;
    *) die "unknown command: $command";;
  esac
}

main "$@"
