package com.bloxbean.cardano.yano.appchain.examples.evidence.demo;

/** Stable, non-reflecting runner failure codes. */
public enum DemoError {
    INVALID_ARGUMENT,
    INVALID_CONFIG,
    UNKNOWN_CONFIG_KEY,
    MISSING_CONFIG_KEY,
    INVALID_SECRET_FILE,
    INSECURE_SECRET_FILE,
    SECRET_FILE_UNAVAILABLE,
    SERVICE_TIMEOUT,
    INITIALIZATION_FAILED,
    SAMPLE_INVALID,
    SUBMISSION_FAILED,
    STORAGE_FAILED,
    NOTIFICATION_FAILED,
    STATE_PROOF_FAILED,
    EFFECT_PROOF_FAILED,
    EXTERNAL_STATE_MISMATCH,
    CLUSTER_DIVERGED,
    ANCHOR_UNAVAILABLE,
    REPORT_WRITE_FAILED,
    UI_START_FAILED,
    INTERNAL_ERROR
}
