package com.bloxbean.cardano.yano.appchain.eutxo.demo;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.Locale;
import java.util.Set;

/**
 * ADR-UTXO-009 §13.2: a settlement operator identity supplied by the person
 * running the deployment, for PUBLIC networks where the packaged demo actors
 * (whose seeds come from a published formula) would be a giveaway.
 *
 * <p>Mirrors the preprod anchor key: an owner-only file holding ONE lowercase
 * 64-hex raw Ed25519 seed, generated by the operator —
 * <pre>{@code
 * mkdir -m 700 ./private-settlement
 * (umask 077; openssl rand -hex 32 > ./private-settlement/operator.seed)
 * }</pre>
 *
 * <p>The remaining actors are derived from that one seed by domain-separated
 * hashing, so an operator manages a single file. The payout destination is
 * deliberately the operator's own address: settled funds return to the key
 * that paid for the deployment unless a chain is configured otherwise.
 */
public record SettlementOperatorIdentity(
        byte[] operatorSeed,
        String operatorAddress,
        byte[] depositorL2Seed,
        byte[] withdrawalL2Seed,
        String payoutAddress
) {
    /** Domain tag; distinct from the demo actors' "yano-showcase-demo-actor:". */
    private static final String DOMAIN = "yano-settlement-operator:";

    /**
     * Load an operator identity from {@code keyFile}.
     *
     * @throws IllegalArgumentException if the file is missing, not exactly one
     *                                  64-hex seed, or readable by anyone else
     */
    public static SettlementOperatorIdentity fromKeyFile(Path keyFile) {
        byte[] seed = readSeed(keyFile);
        return new SettlementOperatorIdentity(
                seed,
                ShowcaseSettlementPlan.enterprise(seed),
                derive(seed, "depositor"),
                derive(seed, "withdrawal"),
                ShowcaseSettlementPlan.enterprise(seed));
    }

    /** The packaged devnet demo actors — public keys, devnet only. */
    public static SettlementOperatorIdentity demo() {
        return new SettlementOperatorIdentity(
                ShowcaseSettlementPlan.OPERATOR_SEED,
                ShowcaseSettlementPlan.OPERATOR_ADDRESS,
                ShowcaseSettlementPlan.DEPOSITOR_L2_SEED,
                ShowcaseSettlementPlan.WITHDRAWAL_L2_SEED,
                ShowcaseSettlementPlan.PAYOUT_ADDRESS);
    }

    // ------------------------------------------------------------------

    private static byte[] readSeed(Path keyFile) {
        if (keyFile == null || !Files.isRegularFile(keyFile)) {
            throw new IllegalArgumentException(
                    "settlement operator key file not found: " + keyFile);
        }
        requireOwnerOnly(keyFile);
        String text;
        try {
            text = Files.readString(keyFile, StandardCharsets.UTF_8).trim();
        } catch (Exception failure) {
            throw new IllegalArgumentException(
                    "cannot read settlement operator key file: " + keyFile,
                    failure);
        }
        if (text.length() != 64
                || !text.equals(text.toLowerCase(Locale.ROOT))
                || !text.matches("[0-9a-f]{64}")) {
            throw new IllegalArgumentException(keyFile + " must contain exactly"
                    + " one lowercase 64-hex raw Ed25519 seed (generate one:"
                    + " openssl rand -hex 32). A mnemonic or CIP-1852 account"
                    + " is NOT the raw seed this option expects.");
        }
        return HexFormat.of().parseHex(text);
    }

    /** A key readable by the group or the world is already compromised. */
    private static void requireOwnerOnly(Path keyFile) {
        try {
            Set<java.nio.file.attribute.PosixFilePermission> permissions =
                    Files.getPosixFilePermissions(keyFile);
            boolean shared = permissions.stream().anyMatch(permission ->
                    permission.name().startsWith("GROUP_")
                            || permission.name().startsWith("OTHERS_"));
            if (shared) {
                throw new IllegalArgumentException(keyFile + " is group- or"
                        + " world-accessible; run: chmod 600 " + keyFile);
            }
        } catch (UnsupportedOperationException noPosix) {
            // Non-POSIX filesystem: the OS enforces its own ACLs.
        } catch (java.io.IOException failure) {
            throw new IllegalArgumentException(
                    "cannot inspect permissions of " + keyFile, failure);
        }
    }

    private static byte[] derive(byte[] seed, String actor) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            digest.update((DOMAIN + actor + ':').getBytes(StandardCharsets.UTF_8));
            digest.update(seed);
            return digest.digest();
        } catch (Exception impossible) {
            throw new IllegalStateException(impossible);
        }
    }

    @Override
    public byte[] operatorSeed() {
        return operatorSeed.clone();
    }

    @Override
    public byte[] depositorL2Seed() {
        return depositorL2Seed.clone();
    }

    @Override
    public byte[] withdrawalL2Seed() {
        return withdrawalL2Seed.clone();
    }

    /** Never let a seed reach a log line or an error message. */
    @Override
    public String toString() {
        return "SettlementOperatorIdentity[operator=" + operatorAddress + ']';
    }
}
