package com.bloxbean.cardano.yano.appchain.integration;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Properties;

import static org.assertj.core.api.Assertions.assertThat;

class ContractArtifactResourcesTest {
    private static final String RESOURCE_ROOT =
            "/META-INF/yano/contracts/connectors/v1/";
    private static final String AGGREGATE_HEADER =
            "; Generated by appchain-integration-contracts. Do not edit this file.\n"
                    + "; The ordered source fragments are published beside this aggregate.\n\n";
    private static final List<String> FRAGMENTS = List.of(
            "common-v1.cddl",
            "detail-v1.cddl",
            "ipfs-pin-v1.cddl",
            "kafka-publish-v1.cddl",
            "object-put-v1.cddl");

    @Test
    void aggregateCddlIsTheDeterministicCompositionOfPublishedFragments() throws IOException {
        String expected = AGGREGATE_HEADER + FRAGMENTS.stream()
                .map(ContractArtifactResourcesTest::readResourceUnchecked)
                .map(String::trim)
                .reduce((left, right) -> left + "\n\n" + right)
                .orElseThrow() + "\n";
        String aggregate = readResource("connectors-v1.cddl");

        assertThat(aggregate).isEqualTo(expected);
        assertThat(aggregate).contains(
                "kafka-publish-v1 = [",
                "object-put-v1 = [",
                "ipfs-pin-v1 = [",
                "connector-detail-v1 =");
    }

    @Test
    void goldenArtifactPublishesExecutableVectorsAndTheirPreimages() throws IOException {
        Properties vectors = new Properties();
        try (var input = resource("golden-vectors.properties")) {
            vectors.load(input);
        }

        List<String> encodedValues = List.of(
                "kafka.command", "kafka.receipt", "kafka.detail", "kafka.detail-hash",
                "object.command", "object.receipt", "object.detail", "object.detail-hash",
                "ipfs.command", "ipfs.receipt", "ipfs.submitted", "ipfs.detail",
                "ipfs.detail-hash", "kafka.destination-fingerprint",
                "object.destination-fingerprint", "object.version-fingerprint",
                "ipfs.target-fingerprint", "ipfs.cid-fingerprint", "ipfs.cid-binary",
                "ipfs.cidv0.normalized-binary");
        assertThat(encodedValues).allSatisfy(name -> {
            String value = vectors.getProperty(name);
            assertThat(value).as(name).isNotBlank().matches("[0-9a-f]+");
            assertThat(value.length()).as(name + " hex length").isEven();
        });

        assertThat(vectors).containsKeys(
                "kafka.command.cddl-root",
                "kafka.receipt.cddl-root",
                "kafka.destination.domain",
                "kafka.destination.target-id",
                "kafka.destination.physical-topic",
                "object.destination.domain",
                "object.destination.target-id",
                "object.destination.bucket",
                "object.destination.prefix",
                "object.destination.relative-key",
                "object.destination.encryption-policy-id",
                "object.destination.retention-policy-id",
                "object.version.domain",
                "object.version.provider-version-id",
                "ipfs.target.domain",
                "ipfs.target.target-id",
                "ipfs.cid.domain",
                "ipfs.cid.input-text",
                "ipfs.cidv0.input-text",
                "object.command.cddl-root",
                "object.receipt.cddl-root",
                "ipfs.command.cddl-root",
                "ipfs.receipt.cddl-root",
                "ipfs.submitted.cddl-root",
                "kafka.detail.cddl-root",
                "object.detail.cddl-root",
                "ipfs.detail.cddl-root");

        String aggregate = readResource("connectors-v1.cddl");
        vectors.stringPropertyNames().stream()
                .filter(name -> name.endsWith(".cddl-root"))
                .map(vectors::getProperty)
                .forEach(root -> assertThat(aggregate).contains("\n" + root + " ="));
    }

    private static String readResourceUnchecked(String name) {
        try {
            return readResource(name);
        } catch (IOException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private static String readResource(String name) throws IOException {
        try (var input = resource(name)) {
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static java.io.InputStream resource(String name) {
        java.io.InputStream input = ContractArtifactResourcesTest.class.getResourceAsStream(
                RESOURCE_ROOT + name);
        if (input == null) {
            throw new IllegalStateException("Missing contract resource: " + name);
        }
        return input;
    }
}
