#!/usr/bin/env bash
# Trust and Status Registry launcher (ADR-049 §2.5): a three-member registry chain on the
# packaged Yano cluster launcher, with the demo genesis generated by yano-trust.
#
#   TRUST_REGISTRY_YANO_HOME=/path/to/yano-x-jvm ./registry.sh up
#   ./registry.sh status | env | seeds | stop | clean
#
# The Yano home is an extracted Yano X JVM distribution (or the showcase's yano/ directory):
# it must hold yano.jar, plugins/, config/, and appchain-cluster/cluster.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CHAIN_ID="${TRUST_REGISTRY_CHAIN_ID:-trust-registry-chain}"
INSTANCE="${TRUST_REGISTRY_INSTANCE:-default}"
NODES="${TRUST_REGISTRY_NODES:-3}"
THRESHOLD="${TRUST_REGISTRY_THRESHOLD:-2}"
HTTP_BASE="${TRUST_REGISTRY_HTTP_BASE:-7270}"
SERVER_BASE="${TRUST_REGISTRY_SERVER_BASE:-9270}"
GATEWAY_PORT="${TRUST_REGISTRY_GATEWAY_PORT:-8481}"
DATA_DIR="${TRUST_REGISTRY_DATA_DIR:-$HOME/.yano-x/trust-registry}"
DEMO_ACTORS=(registry-admin-a registrar-a registrar-b issuer-a)

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
note() { printf '%s\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"; }

usage() {
  cat <<'USAGE'
usage: registry.sh <command> [--instance <name>] [--nodes <n>] [--threshold <n>]
                             [--http-base <port>] [--server-base <port>] [--gateway-port <n>]

  up       generate the demo genesis, write the node configuration, start the members
  status   cluster status
  gateway  start the operator gateway (yano-trust gateway) with the demo seeds, in the background
  env      print the node URL, API key, chain id, and map genesis id as shell exports
  seeds    write the demo actor seed files (owner-only) and print their paths
  stop     stop the members (data is kept)
  clean    stop and delete the instance

Environment: TRUST_REGISTRY_YANO_HOME (required), TRUST_REGISTRY_CLI (yano-trust launcher,
auto-detected), TRUST_REGISTRY_DATA_DIR (default ~/.yano-x/trust-registry).
USAGE
}

resolve_yano_home() {
  YANO_HOME="${TRUST_REGISTRY_YANO_HOME:-}"
  if [ -z "$YANO_HOME" ]; then
    local candidate
    for candidate in "$SCRIPT_DIR/../.." "$SCRIPT_DIR"/../../../build/yano-x/yano-x-jvm-*; do
      if [ -f "$candidate/yano.jar" ] && [ -d "$candidate/plugins" ]; then
        YANO_HOME="$(cd "$candidate" && pwd -P)"
        break
      fi
    done
  fi
  [ -n "$YANO_HOME" ] && [ -f "$YANO_HOME/yano.jar" ] && [ -d "$YANO_HOME/plugins" ] \
    && [ -d "$YANO_HOME/config" ] \
    || die "set TRUST_REGISTRY_YANO_HOME to an extracted Yano X JVM distribution (yano.jar, plugins/, config/)"
  CLUSTER=""
  local launcher
  for launcher in "$YANO_HOME/appchain-cluster/cluster.sh" "$YANO_HOME/examples/appchain-cluster/cluster.sh"; do
    [ -x "$launcher" ] && CLUSTER="$launcher" && break
  done
  [ -n "$CLUSTER" ] || die "cluster launcher not found under $YANO_HOME"
}

resolve_cli() {
  CLI="${TRUST_REGISTRY_CLI:-}"
  if [ -z "$CLI" ]; then
    local candidate
    for candidate in "$YANO_HOME/tools/yano-trust/bin/yano-trust" \
        "$SCRIPT_DIR/../cli/build/install/yano-trust/bin/yano-trust"; do
      if [ -x "$candidate" ]; then CLI="$candidate"; break; fi
    done
  fi
  [ -n "$CLI" ] && [ -x "$CLI" ] \
    || die "yano-trust not found; build it (./gradlew :products:trust-registry:cli:installDist) or set TRUST_REGISTRY_CLI"
}

instance_root() { printf '%s/%s' "$DATA_DIR" "$INSTANCE"; }
home_dir() { printf '%s/home' "$(instance_root)"; }
node_config_dir() { printf '%s/nodes' "$(instance_root)"; }
cluster_dir() { printf '%s/cluster' "$(instance_root)"; }
seed_dir() { printf '%s/seeds' "$(instance_root)"; }
api_key_file() { printf '%s/api-key' "$(instance_root)"; }
genesis_file() { printf '%s/genesis.properties' "$(instance_root)"; }
marker_file() { printf '%s/registry.json' "$(instance_root)"; }

cluster_env() {
  export YANO_HOME="$(home_dir)" YANO_JAR="$YANO_HOME_DIST/yano.jar"
  export YANO_CLUSTER_DIR="$(cluster_dir)"
  export YANO_CLUSTER_HTTP_BASE="$HTTP_BASE" YANO_CLUSTER_SERVER_BASE="$SERVER_BASE"
  export YANO_CLUSTER_NODE_CONFIG_DIR="$(node_config_dir)"
  export YANO_CLUSTER_PRIVATE_CONFIG_DIR="$(instance_root)/private-config"
  export YANO_CLUSTER_API_KEY="$(cat "$(api_key_file)")"
}

write_home() {
  local home; home="$(home_dir)"
  mkdir -p "$home/config"
  chmod 700 "$(instance_root)" "$home"
  cp -R "$YANO_HOME_DIST/config/." "$home/config/"
  cat > "$home/config/application-appchain.yml" <<YAML
# Generated by registry.sh: one governed authenticated-map chain carrying the
# trust-registry-v1 profile (ADR-049). Membership, signing keys, peers, proposer,
# threshold, and the generated genesis are injected per node by appchain-cluster.
yano:
  plugins:
    allow-list:
      - org.yanoproject.x.stdlib
      - org.yanoproject.x.role-workflow
      - org.yanoproject.x.composite
  app-chain:
    chains[0]:
      chain-id: "$CHAIN_ID"
      state-machine: "authenticated-map"
      membership:
        mode: "governed"
      block:
        interval-ms: "1000"
YAML
  # The node resolves plugins/ relative to its home; share the distribution's bundles.
  [ -e "$home/plugins" ] || ln -s "$YANO_HOME_DIST/plugins" "$home/plugins"
}

write_node_configs() {
  local dir i file
  dir="$(node_config_dir)"
  mkdir -p "$dir"; chmod 700 "$dir"
  find "$dir" -maxdepth 1 -type f -name 'node*.properties' -delete
  for ((i=0;i<NODES;i++)); do
    file="$dir/node$i.properties"
    {
      printf 'config_ordinal=275\n'
      printf 'yano.plugins.enabled=true\n'
      printf 'yano.plugins.directory=%s/plugins\n' "$YANO_HOME_DIST"
      # The devnet profile projects L1 history into ./history under the shared home; a
      # registry member needs no L1 history, and members must not share one archive.
      printf 'yano.history.projection.enabled=false\n'
      cat "$(genesis_file)"
    } > "$file"
    chmod 600 "$file"
  done
}

write_seeds() {
  local dir actor
  dir="$(seed_dir)"
  mkdir -p "$dir"; chmod 700 "$dir"
  for actor in "${DEMO_ACTORS[@]}"; do
    # Demo-only deterministic seed shared with TrustRegistryGenesis.demoActorSeed.
    python3 - "$actor" > "$dir/$actor.seed" <<'PY'
import hashlib, sys
print(hashlib.sha256(("yano-trust-registry-demo-actor:" + sys.argv[1]).encode()).hexdigest())
PY
    chmod 600 "$dir/$actor.seed"
  done
}

genesis_id() {
  grep 'state.genesis-id=' "$(genesis_file)" | cut -d= -f2
}

cmd_up() {
  need java; need python3
  resolve_yano_home; YANO_HOME_DIST="$YANO_HOME"; resolve_cli
  [ ! -f "$(marker_file)" ] || die "instance '$INSTANCE' already exists; run stop/clean or pick another --instance"
  mkdir -p "$(instance_root)"; chmod 700 "$(instance_root)"
  write_home
  (umask 077; python3 -c 'import secrets; print(secrets.token_hex(32))' > "$(api_key_file)")
  local members
  members="$(YANO_HOME="$(home_dir)" YANO_JAR="$YANO_HOME_DIST/yano.jar" "$CLUSTER" keys "$NODES" \
    | awk 'NR > 1 {print $3}' | paste -sd, -)"
  [ -n "$members" ] || die "could not derive member keys from the cluster launcher"
  (umask 077; "$CLI" genesis --demo --chain "$CHAIN_ID" --members "$members" --threshold "$THRESHOLD" \
    --chain-index 0 --output "$(genesis_file)" >/dev/null)
  grep -q 'state.genesis-id=' "$(genesis_file)" || die "genesis generation produced no properties"
  # Members file for offline verification (yano-trust verify --members), ADR-047 §7 format.
  python3 - "$(instance_root)/members.json" "$CHAIN_ID" "$THRESHOLD" "$members" <<'PY'
import json, sys
path, chain, threshold, members = sys.argv[1:]
with open(path, "w") as handle:
    json.dump({"chainId": chain, "memberKeysHex": members.split(","), "threshold": int(threshold)},
              handle, indent=2)
    handle.write("\n")
PY
  write_node_configs
  write_seeds
  python3 - "$(marker_file)" "$INSTANCE" "$CHAIN_ID" "$NODES" "$THRESHOLD" "$HTTP_BASE" "$SERVER_BASE" "$(genesis_id)" "$YANO_HOME_DIST" <<'PY'
import json, os, sys
path, instance, chain, nodes, threshold, http_base, server_base, genesis_id, home = sys.argv[1:]
doc = {"schemaVersion": 1, "instance": instance, "chainId": chain, "nodes": int(nodes),
       "threshold": int(threshold), "httpBase": int(http_base), "serverBase": int(server_base),
       "mapGenesisId": genesis_id, "yanoHome": home}
fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
with os.fdopen(fd, "w") as handle:
    json.dump(doc, handle, indent=2)
    handle.write("\n")
PY
  cluster_env
  "$CLUSTER" start "$NODES"
  note ""
  note "Trust registry '$INSTANCE' is starting: chain $CHAIN_ID, $NODES members, threshold $THRESHOLD"
  note "  node 0:        http://127.0.0.1:$HTTP_BASE/api/v1"
  note "  API key file:  $(api_key_file)"
  note "  map genesis:   $(genesis_id)"
  note "  members file:  $(instance_root)/members.json"
  note "  seeds:         $(seed_dir)/<actor>.seed  (${DEMO_ACTORS[*]})"
  note "  data:          $(instance_root)"
  note "Run './registry.sh env' for shell exports; the first write needs --genesis-id (no block yet)."
}

adopt() {
  [ -f "$(marker_file)" ] || die "instance '$INSTANCE' does not exist; run up first"
  python3 - "$(marker_file)" <<'PY' > "$(instance_root)/.env.tmp"
import json, sys
doc = json.load(open(sys.argv[1]))
for key, name in (("chainId", "CHAIN_ID"), ("nodes", "NODES"), ("threshold", "THRESHOLD"),
                  ("httpBase", "HTTP_BASE"), ("serverBase", "SERVER_BASE"), ("yanoHome", "YANO_HOME_DIST")):
    print(f"{name}={doc[key]}")
PY
  # shellcheck disable=SC1090
  . "$(instance_root)/.env.tmp"
  rm -f "$(instance_root)/.env.tmp"
  YANO_HOME="$YANO_HOME_DIST"; resolve_yano_home; YANO_HOME_DIST="$YANO_HOME"
}

stop_gateway() {
  local pidfile="$(instance_root)/gateway.pid"
  [ -f "$pidfile" ] || return 0
  kill "$(cat "$pidfile")" 2>/dev/null && note "stopped the gateway (pid $(cat "$pidfile"))"
  rm -f "$pidfile"
}

# The operator gateway (ADR-053 §2.2), started in the background with the demo seeds.
cmd_gateway() {
  adopt
  local log="$(instance_root)/gateway.log" pidfile="$(instance_root)/gateway.pid"
  if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    die "the gateway is already running (pid $(cat "$pidfile"))"
  fi
  [ -d "$(seed_dir)" ] || write_seeds
  YANO_API_KEY="$(cat "$(api_key_file)")" nohup "$CLI" gateway \
    --url "http://127.0.0.1:$HTTP_BASE/api/v1" --chain "$CHAIN_ID" \
    --seeds "$(seed_dir)" --port "$GATEWAY_PORT" > "$log" 2>&1 &
  echo $! > "$pidfile"
  sleep 4
  kill -0 "$(cat "$pidfile")" 2>/dev/null || { rm -f "$pidfile"; die "the gateway failed to start; see $log"; }
  local token
  token="$(grep -m 1 'token:' "$log" | awk '{print $2}')"
  (umask 077; printf '%s\n' "$token" > "$(instance_root)/gateway-token")
  note "gateway on http://127.0.0.1:$GATEWAY_PORT signing for ${DEMO_ACTORS[*]} (log $log)"
  note "  token: $token"
  note "  the console's Write entries view takes this URL and token."
}

cmd_env() {
  adopt
  printf 'export YANO_TRUST_URL=%q\n' "http://127.0.0.1:$HTTP_BASE/api/v1"
  printf 'export YANO_TRUST_CHAIN=%q\n' "$CHAIN_ID"
  printf 'export YANO_API_KEY=%q\n' "$(cat "$(api_key_file)")"
  printf 'export YANO_TRUST_GENESIS_ID=%q\n' "$(genesis_id)"
  printf 'export YANO_TRUST_SEEDS=%q\n' "$(seed_dir)"
  printf 'export YANO_TRUST_MEMBERS=%q\n' "$(instance_root)/members.json"
  printf 'export TRUST_GATEWAY_URL=%q\n' "http://127.0.0.1:$GATEWAY_PORT"
  [ ! -f "$(instance_root)/gateway-token" ] \
    || printf 'export TRUST_GATEWAY_TOKEN=%q\n' "$(cat "$(instance_root)/gateway-token")"
}

main() {
  local command="${1:-}"; shift || true
  while [ $# -gt 0 ]; do
    case "$1" in
      --instance) INSTANCE="${2:?}"; shift 2;;
      --nodes) NODES="${2:?}"; shift 2;;
      --threshold) THRESHOLD="${2:?}"; shift 2;;
      --http-base) HTTP_BASE="${2:?}"; shift 2;;
      --server-base) SERVER_BASE="${2:?}"; shift 2;;
      --gateway-port) GATEWAY_PORT="${2:?}"; shift 2;;
      -h|--help) usage; exit 0;;
      *) die "unknown option: $1";;
    esac
  done
  [[ "$INSTANCE" =~ ^[A-Za-z0-9._-]{1,64}$ ]] || die "invalid instance name"
  [[ "$NODES" =~ ^[0-9]+$ ]] && [ "$NODES" -ge 1 ] && [ "$NODES" -le 32 ] || die "--nodes must be 1-32"
  [[ "$THRESHOLD" =~ ^[0-9]+$ ]] && [ "$THRESHOLD" -ge 1 ] && [ "$THRESHOLD" -le "$NODES" ] \
    || die "--threshold must be between 1 and the node count"
  case "$command" in
    up) cmd_up;;
    status) adopt; cluster_env; "$CLUSTER" status;;
    gateway) cmd_gateway;;
    env) cmd_env;;
    seeds) adopt; write_seeds; ls -1 "$(seed_dir)";;
    stop) adopt; stop_gateway; cluster_env; "$CLUSTER" stop;;
    clean) adopt; stop_gateway; cluster_env; "$CLUSTER" clean || true; rm -rf -- "$(instance_root)"; note "removed $(instance_root)";;
    ""|help|-h|--help) usage;;
    *) die "unknown command: $command";;
  esac
}

main "$@"
