package com.bloxbean.cardano.yano.appchain.devtools;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Map;
import java.util.TreeMap;

/** Deterministic deployment-manifest export derived from a validated project. */
final class AppChainGitOpsExporter {
    static final String LOCK_FILE = "gitops.lock";

    enum Target {
        HELM("helm"), KUSTOMIZE("kustomize");

        private final String id;

        Target(String id) {
            this.id = id;
        }

        String id() {
            return id;
        }

        static Target parse(String value) {
            for (Target target : values()) {
                if (target.id.equals(value)) return target;
            }
            throw new IllegalArgumentException("GitOps target must be helm or kustomize");
        }
    }

    private final AppChainProjectRenderer renderer;
    private final AppChainProjectResolver resolver;
    private final ObjectMapper json;

    AppChainGitOpsExporter(
            AppChainProjectRenderer renderer,
            AppChainProjectResolver resolver) {
        this.renderer = java.util.Objects.requireNonNull(renderer, "renderer");
        this.resolver = java.util.Objects.requireNonNull(resolver, "resolver");
        this.json = new ObjectMapper()
                .enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION)
                .enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS)
                .enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
    }

    AppChainProjectModel.GitOpsResult export(Path project, Target target, Path output)
            throws IOException {
        if (target == null) throw new IllegalArgumentException("GitOps target is required");
        AppChainProjectModel.ProjectValidation validation = renderer.validate(project);
        AppChainProjectModel.Blueprint blueprint = renderer.readBlueprint(project);
        if ("devnet".equals(blueprint.spec().network())) {
            throw new IllegalArgumentException(
                    "GitOps export requires preview, preprod, or mainnet; devnet has ephemeral genesis inputs");
        }
        AppChainProjectModel.Resolution resolution = resolver.resolve(blueprint);
        Path root = safeEmptyOutput(output);
        Files.createDirectories(root);

        TreeMap<String, byte[]> files = target == Target.HELM
                ? helm(resolution, validation.lock())
                : kustomize(resolution, validation.lock());
        TreeMap<String, String> digests = new TreeMap<>();
        for (Map.Entry<String, byte[]> file : files.entrySet()) {
            write(root, file.getKey(), file.getValue());
            digests.put(file.getKey(), AppChainProjectCatalog.sha256(file.getValue()));
        }
        AppChainProjectModel.GitOpsLock lock = new AppChainProjectModel.GitOpsLock(
                "yano.bloxbean.com/v1alpha1",
                "AppChainGitOpsLock",
                target.id(),
                validation.lock().blueprintDigest(),
                validation.lock().resolvedConfigDigest(),
                validation.lock().catalogDigests().get("releaseIndex"),
                Map.copyOf(digests));
        write(root, LOCK_FILE, json.writerWithDefaultPrettyPrinter().writeValueAsBytes(lock));
        return new AppChainProjectModel.GitOpsResult(
                "GITOPS_EXPORTED", target.id(), files.size(), lock);
    }

    private TreeMap<String, byte[]> kustomize(
            AppChainProjectModel.Resolution resolution,
            AppChainProjectModel.Lock sourceLock) {
        int members = members(resolution);
        TreeMap<String, byte[]> files = commonConfig(resolution, sourceLock, "files/");
        files.put("README.md", utf8(kustomizeReadme(resolution)));
        StringBuilder kustomization = new StringBuilder("""
                # Generated by yano appchain gitops; regenerate from the validated project.
                apiVersion: kustomize.config.k8s.io/v1beta1
                kind: Kustomization
                resources:
                """);
        for (int node = 0; node < members; node++) {
            kustomization.append("  - node").append(node).append(".yaml\n");
        }
        kustomization.append("configMapGenerator:\n");
        for (int node = 0; node < members; node++) {
            kustomization.append("  - name: node").append(node).append("-config\n")
                    .append("    files:\n")
                    .append("      - shared-consensus.yaml=files/shared-consensus.yaml\n")
                    .append("      - node.yaml=files/node").append(node)
                    .append(".yaml\n");
        }
        kustomization.append("generatorOptions:\n  disableNameSuffixHash: true\n")
                .append("images:\n  - name: yano-runtime\n")
                .append("    newName: example.invalid/yano\n    newTag: replace-me\n");
        files.put("kustomization.yaml", utf8(kustomization.toString()));
        for (int node = 0; node < members; node++) {
            files.put("node" + node + ".yaml", utf8(kustomizeNode(
                    resolution.blueprint().spec().network(), node)));
        }
        return files;
    }

    private TreeMap<String, byte[]> helm(
            AppChainProjectModel.Resolution resolution,
            AppChainProjectModel.Lock sourceLock) {
        int members = members(resolution);
        TreeMap<String, byte[]> files = commonConfig(resolution, sourceLock, "files/");
        String name = resolution.blueprint().metadata().name();
        files.put("Chart.yaml", utf8("""
                apiVersion: v2
                name: %s
                description: Deterministic Yano app-chain deployment generated from appchain.lock
                type: application
                version: 0.1.0
                appVersion: "%s"
                """.formatted(name, resolution.blueprint().spec().yanoVersion())));
        StringBuilder values = new StringBuilder("""
                image:
                  repository: example.invalid/yano
                  tag: replace-me
                  pullPolicy: IfNotPresent
                network: %s
                storage:
                  size: 20Gi
                  storageClassName: ""
                nodes:
                """.formatted(resolution.blueprint().spec().network()));
        for (int node = 0; node < members; node++) {
            values.append("  - name: node").append(node).append("\n")
                    .append("    configFile: files/node").append(node).append(".yaml\n")
                    .append("    secretName: yano-appchain-node").append(node).append("\n");
        }
        files.put("values.yaml", utf8(values.toString()));
        files.put("templates/nodes.yaml", utf8(helmNodes()));
        files.put("templates/NOTES.txt", utf8("""
                Verify every node-specific Secret exists, then inspect rollout status.
                This chart never creates or prints signing material.
                """));
        files.put("README.md", utf8(helmReadme(resolution)));
        return files;
    }

    private TreeMap<String, byte[]> commonConfig(
            AppChainProjectModel.Resolution resolution,
            AppChainProjectModel.Lock sourceLock,
            String prefix) {
        TreeMap<String, byte[]> files = new TreeMap<>();
        files.put(prefix + "shared-consensus.yaml",
                utf8(gitOpsYaml(resolution.consensusProperties())));
        int members = members(resolution);
        for (int node = 0; node < members; node++) {
            files.put(prefix + "node" + node + ".yaml", utf8(
                    AppChainProjectRenderer.nodeYaml(
                            resolution, node, members,
                            AppChainProjectRenderer.NodeLayout.KUBERNETES,
                            sourceLock.resolvedConfigDigest(),
                            sourceLock.catalogDigests().get("releaseIndex"))));
        }
        return files;
    }

    private static String kustomizeNode(String network, int node) {
        return """
                # Generated by yano appchain gitops; secret values are never generated.
                apiVersion: v1
                kind: Service
                metadata:
                  name: node%d
                spec:
                  selector:
                    app.kubernetes.io/name: node%d
                  ports:
                    - {name: http, port: 8080, targetPort: http}
                    - {name: n2n, port: 13337, targetPort: n2n}
                ---
                apiVersion: apps/v1
                kind: StatefulSet
                metadata:
                  name: node%d
                spec:
                  serviceName: node%d
                  replicas: 1
                  selector:
                    matchLabels:
                      app.kubernetes.io/name: node%d
                  template:
                    metadata:
                      labels:
                        app.kubernetes.io/name: node%d
                    spec:
                      containers:
                        - name: yano
                          image: yano-runtime
                          imagePullPolicy: IfNotPresent
                          envFrom:
                            - secretRef:
                                name: yano-appchain-node%d
                          env:
                            - {name: YANO_PROFILE, value: "%s"}
                            - name: QUARKUS_CONFIG_LOCATIONS
                              value: /etc/yano/shared-consensus.yaml,/etc/yano/node.yaml
                          ports:
                            - {name: http, containerPort: 8080}
                            - {name: n2n, containerPort: 13337}
                          readinessProbe:
                            httpGet: {path: /q/health/ready, port: http}
                          volumeMounts:
                            - {name: config, mountPath: /etc/yano, readOnly: true}
                            - {name: data, mountPath: /var/lib/yano}
                      volumes:
                        - name: config
                          configMap: {name: node%d-config}
                  volumeClaimTemplates:
                    - metadata: {name: data}
                      spec:
                        accessModes: [ReadWriteOnce]
                        resources:
                          requests: {storage: 20Gi}
                """.formatted(node, node, node, node, node, node, node, network, node);
    }

    private static String helmNodes() {
        return """
                {{- range $node := .Values.nodes }}
                ---
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: {{ $node.name }}-config
                data:
                  shared-consensus.yaml: |-
                {{ $.Files.Get "files/shared-consensus.yaml" | indent 4 }}
                  node.yaml: |-
                {{ $.Files.Get $node.configFile | indent 4 }}
                ---
                apiVersion: v1
                kind: Service
                metadata:
                  name: {{ $node.name }}
                spec:
                  selector: {app.kubernetes.io/name: {{ $node.name }}}
                  ports:
                    - {name: http, port: 8080, targetPort: http}
                    - {name: n2n, port: 13337, targetPort: n2n}
                ---
                apiVersion: apps/v1
                kind: StatefulSet
                metadata:
                  name: {{ $node.name }}
                spec:
                  serviceName: {{ $node.name }}
                  replicas: 1
                  selector:
                    matchLabels: {app.kubernetes.io/name: {{ $node.name }}}
                  template:
                    metadata:
                      labels: {app.kubernetes.io/name: {{ $node.name }}}
                    spec:
                      containers:
                        - name: yano
                          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
                          imagePullPolicy: {{ $.Values.image.pullPolicy }}
                          envFrom:
                            - secretRef: {name: {{ $node.secretName }}}
                          env:
                            - {name: YANO_PROFILE, value: {{ $.Values.network | quote }}}
                            - name: QUARKUS_CONFIG_LOCATIONS
                              value: /etc/yano/shared-consensus.yaml,/etc/yano/node.yaml
                          ports:
                            - {name: http, containerPort: 8080}
                            - {name: n2n, containerPort: 13337}
                          readinessProbe:
                            httpGet: {path: /q/health/ready, port: http}
                          volumeMounts:
                            - {name: config, mountPath: /etc/yano, readOnly: true}
                            - {name: data, mountPath: /var/lib/yano}
                      volumes:
                        - name: config
                          configMap: {name: {{ $node.name }}-config}
                  volumeClaimTemplates:
                    - metadata: {name: data}
                      spec:
                        accessModes: [ReadWriteOnce]
                        {{- if $.Values.storage.storageClassName }}
                        storageClassName: {{ $.Values.storage.storageClassName }}
                        {{- end }}
                        resources:
                          requests: {storage: {{ $.Values.storage.size }}}
                {{- end }}
                """;
    }

    private static String kustomizeReadme(AppChainProjectModel.Resolution resolution) {
        return gitOpsReadme(resolution, """
                1. Replace the image in `kustomization.yaml` with the release-pinned runtime image.
                2. Create `yano-appchain-nodeN` Secrets out of band for every node.
                3. Run `kustomize build .` and review the result before applying it.
                """);
    }

    private static String helmReadme(AppChainProjectModel.Resolution resolution) {
        return gitOpsReadme(resolution, """
                1. Pin `image.repository` and `image.tag` in a reviewed values file.
                2. Create the `secretName` declared for every node out of band.
                3. Run `helm template` and review the result before installing it.
                """);
    }

    private static String gitOpsReadme(
            AppChainProjectModel.Resolution resolution, String instructions) {
        return """
                # Generated Yano app-chain deployment

                This is a deterministic derivative of a validated `%s` project for network `%s`.
                `gitops.lock` binds every generated file to the source blueprint, resolved config,
                and release catalog. Regenerate after any project change.

                %s
                The runtime image must accept `YANO_PROFILE`, `QUARKUS_CONFIG_LOCATIONS`, ports
                8080/13337, and `/var/lib/yano/chainstate`. Generated manifests reference
                per-node Kubernetes Secrets but never contain private values. Signed third-party
                plugin artifacts must be verified and added to the runtime image separately.
                """.formatted(resolution.recipe().id(),
                resolution.blueprint().spec().network(), instructions);
    }

    private static String gitOpsYaml(Map<String, String> values) {
        return AppChainYamlConfigRenderer.render(values,
                "# Generated by yano appchain gitops; regenerate from appchain.yaml.\n");
    }

    private static int members(AppChainProjectModel.Resolution resolution) {
        return resolution.blueprint().spec().chains().getFirst().topology().members();
    }

    private static Path safeEmptyOutput(Path output) throws IOException {
        if (output == null) throw new IOException("GitOps output directory is required");
        Path root = output.toAbsolutePath().normalize();
        if (root.getFileName() == null || root.getParent() == null) {
            throw new IOException("GitOps output must name a specific directory");
        }
        if (Files.exists(root, LinkOption.NOFOLLOW_LINKS)) {
            if (Files.isSymbolicLink(root)
                    || !Files.isDirectory(root, LinkOption.NOFOLLOW_LINKS)) {
                throw new IOException("GitOps output must be a non-symlink directory");
            }
            try (var children = Files.list(root)) {
                if (children.findAny().isPresent()) {
                    throw new IOException("GitOps output directory must be empty");
                }
            }
        }
        return root;
    }

    private static void write(Path root, String name, byte[] bytes) throws IOException {
        Path file = root.resolve(name).normalize();
        if (!file.startsWith(root) || name.startsWith("/") || name.contains("..")) {
            throw new IOException("GitOps file path is unsafe");
        }
        Files.createDirectories(file.getParent());
        Files.write(file, bytes, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
    }

    private static byte[] utf8(String value) {
        return value.getBytes(StandardCharsets.UTF_8);
    }
}
