package com.bloxbean.cardano.yano.appchain.devtools;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/** Deterministic, no-silent-overwrite project renderer. */
final class AppChainProjectRenderer {
    enum NodeLayout { HOST, COMPOSE, KUBERNETES }

    static final String BLUEPRINT_FILE = "appchain.yaml";
    static final String LOCK_FILE = "appchain.lock";
    static final int MAX_BLUEPRINT_BYTES = 1_048_576;
    static final int MAX_GENERATED_FILE_BYTES = 4 * 1_048_576;

    private static final String GENERATED = "# Generated by yano appchain; edit appchain.yaml, then render.\n";
    private static final Set<PosixFilePermission> EXECUTABLE = EnumSet.of(
            PosixFilePermission.OWNER_READ,
            PosixFilePermission.OWNER_WRITE,
            PosixFilePermission.OWNER_EXECUTE,
            PosixFilePermission.GROUP_READ,
            PosixFilePermission.GROUP_EXECUTE,
            PosixFilePermission.OTHERS_READ,
            PosixFilePermission.OTHERS_EXECUTE);

    private final AppChainProjectCatalog catalog;
    private final AppChainProjectResolver resolver;
    private final ObjectMapper json;
    private final ObjectMapper yaml;

    AppChainProjectRenderer(
            AppChainProjectCatalog catalog,
            AppChainProjectResolver resolver) {
        this.catalog = java.util.Objects.requireNonNull(catalog, "catalog");
        this.resolver = java.util.Objects.requireNonNull(resolver, "resolver");
        this.json = configured(new ObjectMapper());
        this.yaml = configured(new ObjectMapper(new YAMLFactory()));
    }

    AppChainProjectModel.Lock initialize(
            Path project,
            AppChainProjectModel.Blueprint blueprint) throws IOException {
        Path root = safeRoot(project);
        requireEmptyOrMissing(root);
        Files.createDirectories(root);
        byte[] blueprintBytes = yaml.writerWithDefaultPrettyPrinter()
                .writeValueAsBytes(blueprint);
        Files.write(root.resolve(BLUEPRINT_FILE), blueprintBytes,
                StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
        return render(root, blueprint, null, blueprintBytes);
    }

    AppChainProjectModel.Lock render(Path project) throws IOException {
        Path root = safeRoot(project);
        Path blueprintPath = root.resolve(BLUEPRINT_FILE);
        byte[] blueprintBytes = boundedFile(blueprintPath, MAX_BLUEPRINT_BYTES, "blueprint");
        AppChainProjectModel.Blueprint blueprint = yaml.readValue(
                blueprintBytes, AppChainProjectModel.Blueprint.class);
        Path lockPath = root.resolve(LOCK_FILE);
        AppChainProjectModel.Lock prior = Files.isRegularFile(lockPath)
                ? readPriorLock(root) : null;
        if (prior == null) {
            requireBlueprintOnly(root);
        } else {
            verifyGeneratedFiles(root, prior.generatedFiles());
        }
        return render(root, blueprint, prior, blueprintBytes);
    }

    AppChainProjectModel.Blueprint readBlueprint(Path project) throws IOException {
        byte[] bytes = boundedFile(safeRoot(project).resolve(BLUEPRINT_FILE),
                MAX_BLUEPRINT_BYTES, "blueprint");
        return yaml.readValue(bytes, AppChainProjectModel.Blueprint.class);
    }

    AppChainProjectModel.ProjectValidation validate(Path project) throws IOException {
        Path root = safeRoot(project);
        byte[] blueprintBytes = boundedFile(root.resolve(BLUEPRINT_FILE),
                MAX_BLUEPRINT_BYTES, "blueprint");
        AppChainProjectModel.Blueprint blueprint = yaml.readValue(
                blueprintBytes, AppChainProjectModel.Blueprint.class);
        AppChainProjectModel.Lock lock = readPriorLock(root);
        verifyGeneratedFiles(root, lock.generatedFiles());
        requireEqual("blueprint digest", AppChainProjectCatalog.sha256(blueprintBytes),
                lock.blueprintDigest());
        requireEqual("catalog digests", catalog.digests(), lock.catalogDigests());

        AppChainProjectModel.Resolution resolution = resolver.resolve(blueprint);
        requireEqual("Yano version", blueprint.spec().yanoVersion(), lock.yanoVersion());
        requireEqual("runtime", blueprint.spec().runtime().type(), lock.runtime());
        requireEqual("deployment", blueprint.spec().deployment().target(), lock.deployment());
        requireEqual("network", blueprint.spec().network(), lock.network());
        requireEqual("recipe", resolution.recipe().id() + ":" + resolution.recipe().version(),
                lock.recipe());
        requireEqual("selected capabilities", resolution.selectedCapabilities(),
                lock.selectedCapabilities());
        requireEqual("implied capabilities", resolution.impliedCapabilities(),
                lock.impliedCapabilities());
        requireEqual("artifacts", resolution.artifacts(), lock.artifacts());
        requireEqual("consensus values", resolution.consensusProperties(), lock.consensusValues());
        String resolvedDigest = AppChainProjectCatalog.sha256(
                json.writeValueAsBytes(new TreeMap<>(resolution.consensusProperties())));
        requireEqual("resolved config digest", resolvedDigest, lock.resolvedConfigDigest());
        return new AppChainProjectModel.ProjectValidation(lock,
                lock.generatedFiles().size(), lock.acknowledgements().size());
    }

    AppChainProjectModel.Lock readLock(Path project) throws IOException {
        return readPriorLock(safeRoot(project));
    }

    private AppChainProjectModel.Lock render(
            Path root,
            AppChainProjectModel.Blueprint blueprint,
            AppChainProjectModel.Lock prior,
        byte[] blueprintBytes) throws IOException {
        AppChainProjectModel.Resolution resolution = resolver.resolve(blueprint);
        String resolvedDigest = AppChainProjectCatalog.sha256(
                json.writeValueAsBytes(new TreeMap<>(resolution.consensusProperties())));
        TreeMap<String, byte[]> outputs = outputs(resolution, resolvedDigest);
        verifyOutputOwnership(root, outputs.keySet(), prior == null
                ? Set.of() : prior.generatedFiles().keySet());
        if (prior != null) {
            removeStaleGeneratedFiles(root, prior.generatedFiles(), outputs.keySet());
        }
        TreeMap<String, String> digests = new TreeMap<>();
        outputs.forEach((name, bytes) -> digests.put(name,
                AppChainProjectCatalog.sha256(bytes)));
        List<String> acknowledgements = new ArrayList<>();
        if (resolution.bootstrapRequired()) {
            acknowledgements.add("PUBLIC_MEMBER_IDENTITIES_REQUIRED_BEFORE_START");
        }
        if (resolution.selectedCapabilities().contains("state:custom-plugin")) {
            acknowledgements.add("CUSTOM_PLUGIN_REVIEW_AND_METADATA_REQUIRED");
        }
        AppChainProjectModel.Lock lock = new AppChainProjectModel.Lock(
                AppChainProjectModel.API_VERSION,
                AppChainProjectModel.LOCK_KIND,
                "https://yano.dev/schema/appchain-blueprint/v1alpha1",
                AppChainProjectCatalog.sha256(blueprintBytes),
                catalog.digests(),
                blueprint.spec().yanoVersion(),
                blueprint.spec().runtime().type(),
                blueprint.spec().deployment().target(),
                blueprint.spec().network(),
                resolution.recipe().id() + ":" + resolution.recipe().version(),
                resolution.selectedCapabilities(),
                resolution.impliedCapabilities(),
                resolution.artifacts(),
                resolution.consensusProperties(),
                resolvedDigest,
                resolution.validationCoverage(),
                resolution.maturity(),
                List.copyOf(acknowledgements),
                Map.copyOf(digests));

        for (Map.Entry<String, byte[]> output : outputs.entrySet()) {
            writeGenerated(root, output.getKey(), output.getValue());
        }
        byte[] lockBytes = json.writerWithDefaultPrettyPrinter().writeValueAsBytes(lock);
        writeGenerated(root, LOCK_FILE, lockBytes);
        markScriptsExecutable(root, outputs.keySet());
        return lock;
    }

    private TreeMap<String, byte[]> outputs(
            AppChainProjectModel.Resolution resolution,
            String resolvedConfigDigest)
            throws IOException {
        TreeMap<String, byte[]> outputs = new TreeMap<>();
        outputs.put("schema/appchain-blueprint.schema.json", catalog.blueprintSchemaBytes());
        outputs.put("schema/appchain-lock.schema.json", catalog.lockSchemaBytes());
        outputs.put("schema/appchain-capability-catalog.json", catalog.capabilityBytes());
        outputs.put("schema/appchain-recipe-catalog.json", catalog.recipeBytes());
        outputs.put("schema/appchain-release-capability-index.json",
                catalog.releaseIndexBytes());
        outputs.put("schema/appchain-first-party-metadata.json",
                catalog.firstPartyMetadataBytes());
        outputs.put("schema/appchain-metadata-trust.schema.json",
                catalog.metadataTrustSchemaBytes());
        outputs.put("schema/appchain-gitops-lock.schema.json",
                catalog.gitOpsLockSchemaBytes());
        outputs.put("ai/configure-yano-appchain/SKILL.md", catalog.aiSkillBytes());
        outputs.put("ai/configure-yano-appchain/agents/openai.yaml",
                catalog.aiSkillOpenAiBytes());
        outputs.put("config/shared-consensus.yaml", utf8(yamlConfig(
                resolution.consensusProperties())));

        int members = resolution.blueprint().spec().chains().getFirst().topology().members();
        boolean compose = "docker-compose".equals(
                resolution.blueprint().spec().deployment().target());
        NodeLayout layout = compose ? NodeLayout.COMPOSE : NodeLayout.HOST;
        for (int index = 0; index < members; index++) {
            outputs.put("config/nodes/node" + index + ".yaml",
                    utf8(nodeYaml(resolution, index, members, layout,
                            resolvedConfigDigest, catalog.digests().get("releaseIndex"))));
            outputs.put("secrets/node" + index + ".env.example",
                    utf8(secretExample(resolution, index)));
        }
        outputs.put("secrets/README.md", utf8(secretsReadme(resolution)));
        outputs.put("secrets/.gitignore", utf8("*.env\n!.gitignore\n!*.env.example\n"));
        outputs.put("README.md", utf8(readme(resolution)));
        outputs.put("docs/TRUST.md", utf8(trustDocumentation(resolution)));
        outputs.put("docs/BOOTSTRAP.md", utf8(bootstrapDocumentation(resolution)));
        outputs.put("docs/VERIFY.md", utf8(verificationDocumentation(resolution)));
        outputs.put("docs/PREREQUISITES.md", utf8(prerequisiteDocumentation(resolution)));
        outputs.put("plans/prerequisites.yaml", prerequisitePlan(resolution));
        if (usesRoles(resolution)) {
            outputs.put("bootstrap/role-approvals-plan.yaml",
                    utf8(roleBootstrapPlan(resolution)));
            outputs.put("bootstrap/README.md",
                    utf8(roleBootstrapDocumentation(resolution)));
        }
        outputs.put("plugins/README.md", utf8(pluginDocumentation(resolution)));
        outputs.put("scripts/validate", utf8(validateScript()));
        outputs.put("ci/verify", utf8(ciVerifyScript()));
        outputs.put("ci/README.md", utf8(ciReadme()));
        outputs.put(".github/workflows/appchain-verify.yml", utf8(ciWorkflow()));
        if ("devnet".equals(resolution.blueprint().spec().network())) {
            outputs.put("scripts/prepare-devnet", utf8(prepareDevnetScript()));
            outputs.put("runtime/.gitignore", utf8("*\n!.gitignore\n"));
        }
        if (compose) {
            outputs.put("compose.yaml", utf8(compose(resolution, members)));
            outputs.put("scripts/start", utf8(composeStartScript(resolution)));
            outputs.put("scripts/stop", utf8(composeStopScript()));
            outputs.put("scripts/status", utf8(composeStatusScript()));
        } else {
            outputs.put("scripts/start-node", utf8(startNodeScript(resolution)));
            outputs.put("scripts/start", utf8(isDistributed(resolution)
                    ? distributedHostStartScript(resolution)
                    : hostStartScript(resolution, members)));
            outputs.put("scripts/stop", utf8(hostStopScript()));
            outputs.put("scripts/status", utf8(hostStatusScript(members)));
        }
        return outputs;
    }

    private static boolean isDistributed(AppChainProjectModel.Resolution resolution) {
        List<String> hosts = resolution.blueprint().spec().chains().getFirst()
                .topology().nodeHosts();
        return hosts != null && !hosts.isEmpty();
    }

    private static boolean usesRoles(AppChainProjectModel.Resolution resolution) {
        return resolution.selectedCapabilities().contains("state:role-approvals")
                || resolution.selectedCapabilities().contains("state:role-evidence");
    }

    static String yamlConfig(Map<String, String> values) {
        return AppChainYamlConfigRenderer.render(values, GENERATED);
    }

    static String nodeYaml(
            AppChainProjectModel.Resolution resolution,
            int node,
            int members,
            NodeLayout layout,
            String resolvedConfigDigest,
            String releaseCatalogDigest) {
        List<String> declaredHosts = resolution.blueprint().spec().chains().getFirst()
                .topology().nodeHosts();
        AppChainProjectModel.Topology topology = resolution.blueprint().spec().chains()
                .getFirst().topology();
        boolean distributed = declaredHosts != null && !declaredHosts.isEmpty();
        boolean compose = layout == NodeLayout.COMPOSE;
        boolean kubernetes = layout == NodeLayout.KUBERNETES;
        int httpBase = topology.httpPortBase() == null ? 8080 : topology.httpPortBase();
        int serverBase = topology.serverPortBase() == null ? 13337 : topology.serverPortBase();
        int serverPort = compose || kubernetes ? 13337
                : distributed ? serverBase : serverBase + node;
        int httpPort = compose || kubernetes ? 8080
                : distributed ? httpBase : httpBase + node;
        List<String> peers = new ArrayList<>();
        for (int index = 0; index < members; index++) {
            if (index == node) continue;
            String peerHost = compose || kubernetes ? "node" + index
                    : distributed ? declaredHosts.get(index) : "127.0.0.1";
            int peerPort = compose || kubernetes ? 13337
                    : distributed ? serverBase : serverBase + index;
            peers.add(peerHost + ":" + peerPort);
        }
        TreeMap<String, String> values = new TreeMap<>();
        values.put("quarkus.http.host", "0.0.0.0");
        values.put("quarkus.http.port", Integer.toString(httpPort));
        values.put("yano.server.port", Integer.toString(serverPort));
        values.put("yano.storage.path", kubernetes ? "/var/lib/yano/chainstate"
                : compose ? "/app/chainstate"
                : "${YANO_APPCHAIN_DATA_ROOT}/node" + node + "/chainstate");
        if ("devnet".equals(resolution.blueprint().spec().network())) {
            values.put("yano.genesis.shelley-genesis-file", "${YANO_APPCHAIN_GENESIS_FILE}");
            if (node == 0) {
                values.put("yano.block-producer.genesis-timestamp",
                        "${YANO_APPCHAIN_GENESIS_TIMESTAMP}");
            }
        }
        values.put("yano.relay.connection.source-port-reuse", "false");
        values.put("yano.relay.connection.max-connections-per-ip", "500");
        values.put("yano.app-chain.api.keys", "${YANO_APPCHAIN_API_KEYS:}");
        values.put("yano.app-chain.validation.strict", "true");
        values.put("yano.app-chain.dx.resolved-config-digest", resolvedConfigDigest);
        values.put("yano.app-chain.dx.release-catalog-digest", releaseCatalogDigest);
        if ("devnet".equals(resolution.blueprint().spec().network()) && node > 0) {
            values.put("yano.block-producer.enabled", "false");
            values.put("yano.dev-mode", "false");
            values.put("yano.client.enabled", "true");
            values.put("yano.remote.host", compose || kubernetes ? "node0"
                    : distributed ? declaredHosts.getFirst() : "127.0.0.1");
            values.put("yano.remote.port", Integer.toString(
                    compose || kubernetes ? 13337 : serverBase));
        }
        values.putAll(resolution.nodePropertyTemplate());
        String prefix = "yano.app-chain.chains[0].";
        values.put(prefix + "peers", String.join(",", peers));
        return yamlConfig(values);
    }

    private String secretExample(AppChainProjectModel.Resolution resolution, int node) {
        TreeSet<String> references = new TreeSet<>();
        references.add("YANO_APPCHAIN_SIGNING_KEY");
        references.add("YANO_APPCHAIN_API_KEYS");
        for (String capabilityId : resolution.selectedCapabilities()) {
            references.addAll(safeMap(catalog.capability(capabilityId).secretReferences()).values());
        }
        StringBuilder example = new StringBuilder("# Copy to node")
                .append(node)
                .append(".env, chmod 600, and provide private values or references.\n");
        references.forEach(reference -> example.append(reference).append("=\n"));
        return example.toString();
    }

    private byte[] prerequisitePlan(AppChainProjectModel.Resolution resolution)
            throws IOException {
        Map<String, Object> plan = new LinkedHashMap<>();
        plan.put("apiVersion", AppChainProjectModel.API_VERSION);
        plan.put("kind", "AppChainPrerequisitePlan");
        plan.put("recipe", resolution.recipe().id());
        plan.put("primaryOutcome", resolution.recipe().primaryOutcome());
        plan.put("firstCommand", resolution.recipe().firstCommand());
        plan.put("verificationQuery", resolution.recipe().verificationQuery());
        plan.put("acceptanceScenario", resolution.recipe().acceptanceScenario());
        List<Map<String, Object>> artifacts = new ArrayList<>();
        for (String artifactId : resolution.artifacts()) {
            AppChainProjectModel.Artifact artifact = catalog.artifact(artifactId);
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("id", artifact.id());
            item.put("availability", artifact.availability());
            item.put("bundleId", artifact.bundleId());
            item.put("nativePosture", artifact.nativePosture());
            artifacts.add(Map.copyOf(item));
        }
        plan.put("artifacts", List.copyOf(artifacts));
        List<Map<String, Object>> capabilities = new ArrayList<>();
        for (String capabilityId : resolution.selectedCapabilities()) {
            AppChainProjectModel.Capability capability = catalog.capability(capabilityId);
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("id", capability.id());
            item.put("scope", capability.effectiveScope());
            item.put("availability", capability.availability());
            item.put("externalPrerequisites", safeList(capability.externalPrerequisites()));
            item.put("bootstrapRequirements", safeList(capability.bootstrapRequirements()));
            item.put("nonSecretAnswers", safeList(capability.nonSecretAnswers()));
            item.put("secretReferences", new TreeSet<>(
                    safeMap(capability.secretReferences()).values()));
            item.put("documentation", capability.documentation());
            item.put("acceptanceScenario", capability.acceptanceScenario());
            capabilities.add(Map.copyOf(item));
        }
        plan.put("capabilities", List.copyOf(capabilities));
        plan.put("readinessStages", List.of(
                "CONFIG_VALID", "ARTIFACTS_READY", "IDENTITIES_READY",
                "RUNTIME_STARTABLE", "APPLICATION_BOOTSTRAPPED", "EXECUTORS_READY",
                "EXTERNAL_TARGETS_READY", "OUTCOME_READY"));
        return yaml.writerWithDefaultPrettyPrinter().writeValueAsBytes(plan);
    }

    private String prerequisiteDocumentation(AppChainProjectModel.Resolution resolution) {
        StringBuilder document = new StringBuilder("""
                # Artifacts and prerequisites

                This file is generated from the release-pinned capability catalog. `BUNDLED`
                artifacts are present in the named Yano distribution. `FIRST_PARTY_OPTIONAL`
                and `EXPERIMENTAL` artifacts require explicit installation (or native-image
                inclusion) and remain pending until `doctor` verifies the final distribution.
                """);
        document.append("Primary outcome: ")
                .append(resolution.recipe().primaryOutcome()).append("\n\n")
                .append("First command: `").append(resolution.recipe().firstCommand())
                .append("`\n\nVerification: `")
                .append(resolution.recipe().verificationQuery())
                .append("`\n\n## Artifacts\n\n")
                .append("| Artifact | Availability | Native posture |\n")
                .append("|---|---|---|\n");
        for (String artifactId : resolution.artifacts()) {
            AppChainProjectModel.Artifact artifact = catalog.artifact(artifactId);
            document.append("| `").append(artifact.id()).append("` | ")
                    .append(artifact.availability()).append(" | ")
                    .append(artifact.nativePosture()).append(" |\n");
        }
        document.append("\n## Capability readiness\n\n");
        for (String capabilityId : resolution.selectedCapabilities()) {
            AppChainProjectModel.Capability capability = catalog.capability(capabilityId);
            document.append("### `").append(capability.id()).append("`\n\n")
                    .append(capability.description()).append("\n\n")
                    .append("- Availability: `").append(capability.availability())
                    .append("`; maturity: `").append(capability.maturity())
                    .append("`; scope: `").append(capability.effectiveScope()).append("`.\n")
                    .append("- External prerequisites: ")
                    .append(orNone(capability.externalPrerequisites())).append(".\n")
                    .append("- Bootstrap requirements: ")
                    .append(orNone(capability.bootstrapRequirements())).append(".\n")
                    .append("- Documentation: `").append(capability.documentation())
                    .append("`.\n\n");
        }
        document.append("Run `./yano.sh appchain doctor . --distribution <release>` and resolve "
                + "each readiness stage in order. Never put secret values in the blueprint, "
                + "lock, or shared consensus configuration.\n");
        return document.toString();
    }

    private static String orNone(List<String> values) {
        return values == null || values.isEmpty() ? "none" : String.join(", ", values);
    }

    private static String ciVerifyScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                : "${YANO_HOME:?Set YANO_HOME to the extracted, version-matched Yano distribution}"
                "$YANO_HOME/yano.sh" appchain config validate --mode project "$root"
                "$YANO_HOME/yano.sh" appchain doctor "$root" --distribution "$YANO_HOME"
                """;
    }

    private static String ciReadme() {
        return """
                # CI verification

                `verify` performs offline project validation and confirms that the extracted Yano
                distribution matches the project runtime and release capability index. It never
                starts nodes and does not require signing keys or API keys.

                The generated GitHub Actions workflow requires repository variables
                `YANO_DISTRIBUTION_URL` and `YANO_DISTRIBUTION_SHA256`. Pin both to the exact Yano
                release selected by `appchain.yaml`; the download is rejected unless its SHA-256
                matches.
                """;
    }

    private static String ciWorkflow() {
        return """
                # Generated by yano appchain; edit appchain.yaml, then render.
                name: App-chain project verification
                on:
                  pull_request:
                  push:
                    branches: [main]
                permissions:
                  contents: read
                jobs:
                  verify:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: actions/checkout@v4
                      - name: Require pinned Yano distribution
                        env:
                          YANO_DISTRIBUTION_URL: ${{ vars.YANO_DISTRIBUTION_URL }}
                          YANO_DISTRIBUTION_SHA256: ${{ vars.YANO_DISTRIBUTION_SHA256 }}
                        run: |
                          set -euo pipefail
                          test -n "$YANO_DISTRIBUTION_URL"
                          test -n "$YANO_DISTRIBUTION_SHA256"
                          test "${#YANO_DISTRIBUTION_SHA256}" -eq 64
                          case "$YANO_DISTRIBUTION_SHA256" in
                            *[!0-9a-fA-F]*) exit 1 ;;
                          esac
                          download=(curl --fail --location --proto '=https' --tlsv1.2)
                          download+=(--output "$RUNNER_TEMP/yano.zip")
                          "${download[@]}" -- "$YANO_DISTRIBUTION_URL"
                          checksum_line="$YANO_DISTRIBUTION_SHA256  $RUNNER_TEMP/yano.zip"
                          printf '%s' "$checksum_line" | sha256sum --check -
                          unzip -q "$RUNNER_TEMP/yano.zip" -d "$RUNNER_TEMP/yano"
                          YANO_HOME="$(find "$RUNNER_TEMP/yano" -mindepth 1 -maxdepth 1 -type d -print -quit)"
                          test -x "$YANO_HOME/yano.sh"
                          echo "YANO_HOME=$YANO_HOME" >> "$GITHUB_ENV"
                      - name: Validate blueprint, lock, generated files, and distribution
                        run: ./ci/verify
                """;
    }

    private static String secretsReadme(AppChainProjectModel.Resolution resolution) {
        return """
                # Secret provisioning

                Generated configuration contains references, never private values. Copy each
                `nodeN.env.example` to `nodeN.env`, set `YANO_APPCHAIN_SIGNING_KEY`, optionally
                set an unscoped `YANO_APPCHAIN_API_KEYS` value for privileged operator
                diagnostics, and restrict the file to the owning operator. Never commit `*.env`
                files.

                The signing value may be a 32-byte Ed25519 seed or a configured
                `scheme:reference` understood by the selected signer provider.

                Bootstrap status: %s
                """.formatted(resolution.bootstrapRequired()
                ? "public member keys must be added to appchain.yaml before production start."
                : "public member keys are pinned in appchain.yaml and appchain.lock.");
    }

    private static String readme(AppChainProjectModel.Resolution resolution) {
        AppChainProjectModel.Blueprint blueprint = resolution.blueprint();
        int members = blueprint.spec().chains().getFirst().topology().members();
        String target = blueprint.spec().deployment().target();
        return """
                # %s

                Generated from `appchain.yaml` with recipe `%s` for %s members.

                1. Review `appchain.yaml` and `appchain.lock`.
                2. If the lock acknowledges `PUBLIC_MEMBER_IDENTITIES_REQUIRED_BEFORE_START`,
                   add all member public keys under `spec.chains[0].topology.memberKeys` and run
                   `./scripts/validate`, then `./scripts/start`.
                3. Provision `secrets/nodeN.env` from each example on the owning machine.
                4. Set `YANO_HOME` for host deployment or `YANO_IMAGE` for Compose.
                5. Run `./scripts/start`, `./scripts/status`, and `./scripts/stop`.

                Deployment target: `%s`. Consensus defaults are explicit in
                `config/shared-consensus.yaml`; per-node values are isolated in
                `config/nodes`. Generated files are digest-protected by `appchain.lock`.
                """.formatted(blueprint.metadata().name(), resolution.recipe().id(), members, target);
    }

    private static String trustDocumentation(AppChainProjectModel.Resolution resolution) {
        return """
                # Trust model

                Recipe: `%s` (%s). %s

                The lock pins selected capabilities, release artifacts, catalogs, and every
                consensus-shared value. Generated files are digest-protected. Private signing
                material is deliberately excluded and must be provisioned by each operator.

                Custom plugin metadata is declarative and data-only; the tooling never loads
                plugin classes while validating or rendering a project.
                """.formatted(resolution.recipe().id(), resolution.maturity(),
                resolution.recipe().trustStatement());
    }

    private static String bootstrapDocumentation(AppChainProjectModel.Resolution resolution) {
        return """
                # Bootstrap

                1. Collect one public member identity from each operator.
                2. Put the identities in `spec.chains[0].topology.memberKeys` in the same reviewed
                   order on every machine.
                3. Run `./yano.sh appchain config validate --mode project .` and review `appchain.lock`.
                4. Copy the project to each machine; provision only that node's `secrets/nodeN.env`.
                5. Start each node with `scripts/start-node N` or use the generated Compose project.

                Current bootstrap requirement: %s
                """.formatted(resolution.bootstrapRequired()
                ? "public member identities are still required before start."
                : "member identities are pinned and ready for operator verification.");
    }

    private static String roleBootstrapPlan(AppChainProjectModel.Resolution resolution) {
        String chainId = resolution.blueprint().spec().chains().getFirst().chainId();
        String profile = resolution.selectedCapabilities().contains("state:role-evidence")
                ? "role-evidence" : "role-approvals";
        return """
                # Generated non-secret planning template. Replace every REPLACE_* value.
                apiVersion: yano.bloxbean.com/v1alpha1
                kind: RoleBootstrapPlan
                chainId: %s
                profile: %s
                idempotency:
                  beforeEveryOperation: QUERY_COMMITTED_RECORD_AND_VERIFY_PROOF
                  whenAbsent: PROPOSE_APPROVE_TO_THRESHOLD_AND_ACTIVATE
                  whenExactRevisionAndValueMatch: SKIP_AND_RECORD_PROOF
                  whenRevisionOrValueDiffers: FAIL_CLOSED
                  replacement: FORBIDDEN
                organizations:
                  - organizationId: organization-a
                    revision: 1
                    status: ACTIVE
                    metadataCommitment: REPLACE_64_HEX_OR_EMPTY
                  - organizationId: organization-b
                    revision: 1
                    status: ACTIVE
                    metadataCommitment: REPLACE_64_HEX_OR_EMPTY
                actors:
                  - actorId: proposer-a
                    organizationId: organization-a
                    revision: 1
                    roles: [proposer]
                    publicKeys:
                      - keyId: proposer-key-v1
                        publicKey: REPLACE_64_HEX
                        validFromHeight: 1
                        validUntilHeight: 0
                        proofOfPossession: REQUIRED
                  - actorId: reviewer-a
                    organizationId: organization-b
                    revision: 1
                    roles: [reviewer]
                    publicKeys:
                      - keyId: reviewer-key-v1
                        publicKey: REPLACE_64_HEX
                        validFromHeight: 1
                        validUntilHeight: 0
                        proofOfPossession: REQUIRED
                policies:
                  - policyId: application-approval
                    revision: 1
                    proposerRoles: [proposer]
                    clauses:
                      - clauseId: reviewers
                        role: reviewer
                        minimumCount: 1
                        distinctBy: ORGANIZATION
                    rejectionMode: ANY_ELIGIBLE
                    maximumLifetimeBlocks: 1000
                governance:
                  administrators: genesis-app-chain-members
                  threshold: %d
                  sequence: [PROPOSE, APPROVE_TO_THRESHOLD, ACTIVATE]
                  proposalIdsMustBeUnique: true
                verification:
                  organization: organizations/{id}?revision={revision}
                  actor: actors/{id}?revision={revision}
                  policy: policies/{id}?revision={revision}
                  proposal: proposals/{id}
                  stats: stats
                  proofs: responses include proofKey, recordValue, stateRoot, and committedHeight
                """.formatted(chainId, profile, resolution.threshold());
    }

    private static String roleBootstrapDocumentation(
            AppChainProjectModel.Resolution resolution) {
        String chainId = resolution.blueprint().spec().chains().getFirst().chainId();
        String bundle = resolution.selectedCapabilities().contains("state:role-evidence")
                ? "com.bloxbean.cardano.yano.appchain.evidence-profile"
                : "com.bloxbean.cardano.yano.appchain.role-workflow";
        return """
                # Role bootstrap and offline signing

                Review 'role-approvals-plan.yaml'. It is a non-secret plan, not an automatically
                trusted identity claim. Before every governed mutation, query the exact record
                and revision; if it already matches, record the proof and skip it. If an existing
                record differs, stop. Never replace it silently.

                Keep each 32-byte Ed25519 seed in an owner-only file outside this project. These
                commands read that file locally and print only a public key or canonical CBOR hex:

                ```bash
                ./yano.sh appchain role public-key --seed-file /owner-only/actor.seed
                ./yano.sh appchain role key-proof --chain %s --actor proposer-a \\
                  --actor-revision 1 --key proposer-key-v1 --public-key <64-hex> \\
                  --valid-from-height 1 --valid-until-height 0 \\
                  --seed-file /owner-only/actor.seed
                ./yano.sh appchain role sign --action approve --chain %s \\
                  --proposal proposal-001 --policy application-approval \\
                  --policy-revision 1 --payload-domain com.example.order.v1 \\
                  --payload-hash <64-hex> --deadline-height 1000 --actor reviewer-a \\
                  --actor-revision 1 --key reviewer-key-v1 --clause reviewers \\
                  --seed-file /owner-only/reviewer.seed
                ```

                Submit governance records on 'actors.command.v1' and actor proposal/decision
                commands on 'role-approvals.command.v1'. The generic product stores and proves
                the approved payload hash; it does not execute the payload or emit an effect.

                Verify through the read-only domain API:

                ```text
                /api/v1/plugins/%s/organizations/{id}?chain=%s
                /api/v1/plugins/%s/actors/{id}?chain=%s
                /api/v1/plugins/%s/policies/{id}?chain=%s
                /api/v1/plugins/%s/proposals/{id}?chain=%s
                /api/v1/plugins/%s/stats?chain=%s
                ```

                Private keys never belong in the plan, node configuration, Studio, or Yano.
                """.formatted(chainId, chainId,
                bundle, chainId, bundle, chainId, bundle, chainId,
                bundle, chainId, bundle, chainId);
    }

    private static String verificationDocumentation(AppChainProjectModel.Resolution resolution) {
        return """
                # Verification

                Run these checks before deployment and after transferring the project:

                ```bash
                ./yano.sh appchain config validate --mode project .
                ./yano.sh appchain doctor . --distribution /path/to/yano-release.zip
                ./yano.sh appchain diff old/appchain.lock appchain.lock
                export YANO_OPERATOR_API_KEY='provisioned-out-of-band'
                ./yano.sh appchain drift . --peer https://node1.example/api/v1/ \\
                  --peer https://node2.example/api/v1/ \\
                  --api-key-env YANO_OPERATOR_API_KEY
                ```

                Validation coverage is `%s`. A valid result proves blueprint, catalog, lock,
                resolved consensus values, and generated-file digest consistency. It does not
                attest private keys or externally supplied custom plugin code. Drift compares
                only redacted identity categories; it never prints digest values or reads an API
                key from command-line arguments.
                """.formatted(resolution.validationCoverage());
    }

    private String pluginDocumentation(AppChainProjectModel.Resolution resolution) {
        boolean custom = resolution.selectedCapabilities().contains("state:custom-plugin");
        boolean optional = resolution.artifacts().stream().anyMatch(artifact ->
                !"BUNDLED".equals(catalog.artifact(artifact).availability()));
        return """
                # Plugins

                Required release artifacts: %s

                %s
                """.formatted(String.join(", ", resolution.artifacts()), custom
                ? "This project uses the advanced custom-plugin path. Package the reviewed JVM "
                        + "bundle separately, provide its declarative configuration metadata, "
                        + "bind that descriptor to its runtime manifest with the signed trust "
                        + "envelope, run `./yano.sh appchain metadata verify` with a pinned vendor "
                        + "public key, and run doctor against the final distribution. A valid "
                        + "signature authenticates the binding but remains PARTIAL coverage."
                : optional
                        ? "This project selects one or more non-bundled artifacts. Review "
                                + "docs/PREREQUISITES.md, install the exact version-matched "
                                + "bundle explicitly, and use doctor against the final distribution."
                        : "All selected components are first-party artifacts bundled in the "
                                + "named release distribution.");
    }


    private static String prepareDevnetScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                source_file="${1:?Usage: prepare-devnet SOURCE_GENESIS}"
                root="$(cd "$(dirname "$0")/.." && pwd)"
                target="$root/runtime/shelley-genesis.json"
                mkdir -p "$root/runtime"
                [ -f "$target" ] && exit 0
                python3 - "$source_file" "$target" <<'PY'
                import datetime
                import json
                import os
                import sys
                import tempfile

                source, target = sys.argv[1:]
                with open(source, encoding="utf-8") as stream:
                    genesis = json.load(stream)
                start = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(seconds=10)
                genesis["systemStart"] = start.isoformat(timespec="milliseconds").replace("+00:00", "Z")
                genesis["epochLength"] = 500
                descriptor, temporary = tempfile.mkstemp(prefix="genesis-", dir=os.path.dirname(target))
                try:
                    with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
                        json.dump(genesis, stream, indent=2, sort_keys=True)
                        stream.write("\\n")
                    os.chmod(temporary, 0o600)
                    os.replace(temporary, target)
                finally:
                    if os.path.exists(temporary):
                        os.unlink(temporary)
                PY
                """;
    }

    private static String validateScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                : "${YANO_HOME:?Set YANO_HOME to the extracted Yano distribution}"
                exec "$YANO_HOME/yano.sh" appchain render "$root"
                """;
    }

    private static String startNodeScript(AppChainProjectModel.Resolution resolution) {
        String network = resolution.blueprint().spec().network();
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                node="${1:?Usage: start-node NODE_INDEX}"
                root="$(cd "$(dirname "$0")/.." && pwd)"
                : "${YANO_HOME:?Set YANO_HOME to the extracted Yano distribution}"
                secret="$root/secrets/node${node}.env"
                config="$root/config/nodes/node${node}.yaml"
                [ -f "$secret" ] || { echo "Missing $secret" >&2; exit 1; }
                [ -f "$config" ] || { echo "Unknown node index: $node" >&2; exit 1; }
                set -a
                . "$secret"
                set +a
                : "${YANO_APPCHAIN_SIGNING_KEY:?Missing signing key in node env file}"
                export YANO_APPCHAIN_DATA_ROOT="${YANO_APPCHAIN_DATA_ROOT:-$root/data}"
                mkdir -p "$YANO_APPCHAIN_DATA_ROOT/node${node}"
                %s
                export QUARKUS_CONFIG_LOCATIONS="$root/config/shared-consensus.yaml,$config"
                cd "$root"
                exec "$YANO_HOME/yano.sh" "start:%s"
                """.formatted("devnet".equals(network) ? """
                genesis="$root/runtime/shelley-genesis.json"
                [ -f "$genesis" ] || { echo "Run scripts/start to prepare devnet genesis" >&2; exit 1; }
                export YANO_APPCHAIN_GENESIS_FILE="$genesis"
                export YANO_APPCHAIN_GENESIS_TIMESTAMP="$(python3 - "$genesis" <<'PY'
                import datetime, json, sys
                with open(sys.argv[1], encoding="utf-8") as stream:
                    value = json.load(stream)["systemStart"]
                parsed = datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
                print(int(parsed.timestamp() * 1000))
                PY
                )"
                """ : "", network);
    }

    private static String hostStartScript(
            AppChainProjectModel.Resolution resolution,
            int members) {
        AppChainProjectModel.Topology topology = resolution.blueprint().spec().chains()
                .getFirst().topology();
        int httpBase = topology.httpPortBase() == null ? 8080 : topology.httpPortBase();
        String prepare = "devnet".equals(resolution.blueprint().spec().network())
                ? "\"$root/scripts/prepare-devnet\" "
                        + "\"$YANO_HOME/config/network/devnet/shelley-genesis.json\""
                : ":";
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                : "${YANO_HOME:?Set YANO_HOME to the extracted Yano distribution}"
                mkdir -p "$root/run" "$root/logs"
                %s
                for node in $(seq 0 %d); do
                  "$root/scripts/start-node" "$node" >"$root/logs/node${node}.log" 2>&1 &
                  echo $! >"$root/run/node${node}.pid"
                  port=$((%d + node))
                  ready=0
                  for attempt in $(seq 1 90); do
                    if curl -sf "http://127.0.0.1:${port}/q/health/ready" >/dev/null; then
                      ready=1
                      break
                    fi
                    kill -0 "$(cat "$root/run/node${node}.pid")" 2>/dev/null || break
                    sleep 2
                  done
                  if [ "$ready" -ne 1 ]; then
                    echo "node${node} failed readiness; see logs/node${node}.log" >&2
                    "$root/scripts/stop" || true
                    exit 1
                  fi
                done
                echo "Started %d ready node processes; see logs/"
                """.formatted(prepare, members - 1, httpBase, members);
    }

    private static String distributedHostStartScript(
            AppChainProjectModel.Resolution resolution) {
        String prepare = "devnet".equals(resolution.blueprint().spec().network())
                ? "\"$root/scripts/prepare-devnet\" "
                        + "\"$YANO_HOME/config/network/devnet/shelley-genesis.json\""
                : ":";
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                node="${1:?Usage: start NODE_INDEX}"
                root="$(cd "$(dirname "$0")/.." && pwd)"
                : "${YANO_HOME:?Set YANO_HOME to the extracted Yano distribution}"
                %s
                exec "$root/scripts/start-node" "$node"
                """.formatted(prepare);
    }

    private static String hostStopScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                shopt -s nullglob
                records=("$root"/run/node*.pid)
                for record in "${records[@]}"; do
                  pid="$(cat "$record")"
                  kill "$pid" 2>/dev/null || true
                done
                failed=0
                for record in "${records[@]}"; do
                  pid="$(cat "$record")"
                  stopped=0
                  for attempt in $(seq 1 100); do
                    if ! kill -0 "$pid" 2>/dev/null; then
                      stopped=1
                      break
                    fi
                    sleep 0.1
                  done
                  if [ "$stopped" -eq 1 ]; then
                    rm -f "$record"
                  else
                    echo "node process $pid did not stop within 10 seconds" >&2
                    failed=1
                  fi
                done
                exit "$failed"
                """;
    }

    private static String hostStatusScript(int members) {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                for node in $(seq 0 %d); do
                  record="$root/run/node${node}.pid"
                  if [ -f "$record" ] && kill -0 "$(cat "$record")" 2>/dev/null; then
                    echo "node${node}: running"
                  else
                    echo "node${node}: stopped"
                  fi
                done
                """.formatted(members - 1);
    }

    private static String compose(AppChainProjectModel.Resolution resolution, int members) {
        StringBuilder output = new StringBuilder(GENERATED).append("services:\n");
        String network = resolution.blueprint().spec().network();
        AppChainProjectModel.Topology topology = resolution.blueprint().spec().chains()
                .getFirst().topology();
        int httpBase = topology.httpPortBase() == null ? 8080 : topology.httpPortBase();
        int serverBase = topology.serverPortBase() == null ? 13337 : topology.serverPortBase();
        for (int index = 0; index < members; index++) {
            output.append("  node").append(index).append(":\n")
                    .append("    image: ${YANO_IMAGE:?Set YANO_IMAGE}\n");
            if (index > 0) {
                output.append("    depends_on:\n")
                        .append("      node0:\n")
                        .append("        condition: service_healthy\n");
            }
            output
                    .append("    env_file: [./secrets/node").append(index).append(".env]\n")
                    .append("    environment:\n")
                    .append("      YANO_PROFILE: ").append(network).append("\n");
            if ("devnet".equals(network)) {
                output.append("      YANO_APPCHAIN_GENESIS_FILE: ")
                        .append("/project/runtime/shelley-genesis.json\n")
                        .append("      YANO_APPCHAIN_GENESIS_TIMESTAMP: ")
                        .append("${YANO_APPCHAIN_GENESIS_TIMESTAMP:?Run scripts/start}\n");
            }
            output.append("      QUARKUS_CONFIG_LOCATIONS: ")
                    .append("/project/config/shared-consensus.yaml,")
                    .append("/project/config/nodes/node").append(index).append(".yaml\n")
                    .append("    volumes:\n")
                    .append("      - ./:/project:ro\n")
                    .append("      - node").append(index).append("-data:/app/chainstate\n")
                    .append("    ports:\n")
                    .append("      - \"").append(httpBase + index).append(":8080\"\n")
                    .append("      - \"").append(serverBase + index).append(":13337\"\n")
                    .append("    healthcheck:\n")
                    .append("      test: [\"CMD\", \"curl\", \"-fsS\", ")
                    .append("\"http://localhost:8080/q/health/ready\"]\n")
                    .append("      interval: 2s\n")
                    .append("      timeout: 2s\n")
                    .append("      retries: 90\n");
        }
        output.append("volumes:\n");
        for (int index = 0; index < members; index++) {
            output.append("  node").append(index).append("-data: {}\n");
        }
        return output.toString();
    }

    private static String composeStartScript(AppChainProjectModel.Resolution resolution) {
        String prepare = "devnet".equals(resolution.blueprint().spec().network())
                ? """
                : "${YANO_IMAGE:?Set YANO_IMAGE}"
                mkdir -p "$root/runtime"
                base="$root/runtime/shelley-genesis.base.json"
                if [ ! -f "$root/runtime/shelley-genesis.json" ]; then
                  docker run --rm --entrypoint cat "$YANO_IMAGE" \
                    /app/default-config/network/devnet/shelley-genesis.json >"$base"
                  "$root/scripts/prepare-devnet" "$base"
                  rm -f "$base"
                fi
                export YANO_APPCHAIN_GENESIS_TIMESTAMP="$(python3 - \
                  "$root/runtime/shelley-genesis.json" <<'PY'
                import datetime, json, sys
                with open(sys.argv[1], encoding="utf-8") as stream:
                    value = json.load(stream)["systemStart"]
                parsed = datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
                print(int(parsed.timestamp() * 1000))
                PY
                )"
                """ : "";
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                %s
                cd "$root"
                exec docker compose up -d
                """.formatted(prepare);
    }

    private static String composeStopScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                cd "$root"
                exec docker compose down
                """;
    }

    private static String composeStatusScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "$0")/.." && pwd)"
                cd "$root"
                exec docker compose ps
                """;
    }

    private AppChainProjectModel.Lock readPriorLock(Path root) throws IOException {
        byte[] bytes = boundedFile(root.resolve(LOCK_FILE), MAX_BLUEPRINT_BYTES, "lock");
        AppChainProjectModel.Lock lock = json.readValue(bytes, AppChainProjectModel.Lock.class);
        if (!AppChainProjectModel.API_VERSION.equals(lock.apiVersion())
                || !AppChainProjectModel.LOCK_KIND.equals(lock.kind())
                || lock.generatedFiles() == null) {
            throw new IOException("Project lock is not a supported v1alpha1 lock");
        }
        return lock;
    }

    private static void verifyGeneratedFiles(Path root, Map<String, String> expected)
            throws IOException {
        for (Map.Entry<String, String> generated : new TreeMap<>(expected).entrySet()) {
            Path path = resolveGenerated(root, generated.getKey());
            if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
                throw new IOException("Generated file is missing: " + generated.getKey());
            }
            if (Files.size(path) > MAX_GENERATED_FILE_BYTES) {
                throw new IOException("Generated file exceeds safety limit: "
                        + generated.getKey());
            }
            String actual = AppChainProjectCatalog.sha256(Files.readAllBytes(path));
            if (!actual.equals(generated.getValue())) {
                throw new IOException("Generated file has manual edits: " + generated.getKey()
                        + "; move the change into appchain.yaml or reconcile it explicitly");
            }
        }
    }

    private static void removeStaleGeneratedFiles(
            Path root,
            Map<String, String> prior,
            Set<String> retained) throws IOException {
        for (String name : new TreeMap<>(prior).keySet()) {
            if (!retained.contains(name)) {
                Files.deleteIfExists(resolveGenerated(root, name));
            }
        }
    }

    private static void verifyOutputOwnership(
            Path root,
            Set<String> outputs,
            Set<String> priorGenerated) throws IOException {
        for (String name : new java.util.TreeSet<>(outputs)) {
            Path path = resolveGenerated(root, name);
            if (Files.exists(path, LinkOption.NOFOLLOW_LINKS)
                    && !priorGenerated.contains(name)) {
                throw new IOException("Refusing to overwrite user-owned path newly claimed by "
                        + "this renderer version: " + name
                        + "; move or reconcile the file explicitly");
            }
        }
    }

    private static void writeGenerated(Path root, String name, byte[] bytes) throws IOException {
        Path path = resolveGenerated(root, name);
        Files.createDirectories(path.getParent());
        if (Files.exists(path, LinkOption.NOFOLLOW_LINKS) && Files.isSymbolicLink(path)) {
            throw new IOException("Refusing to replace generated symlink: " + name);
        }
        Files.write(path, bytes, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING,
                StandardOpenOption.WRITE);
    }

    private static Path resolveGenerated(Path root, String name) throws IOException {
        Path path = root.resolve(name).normalize();
        if (!path.startsWith(root) || name.startsWith("/") || name.contains("..")) {
            throw new IOException("Generated file path is unsafe");
        }
        Path current = root;
        for (Path segment : root.relativize(path)) {
            current = current.resolve(segment);
            if (Files.exists(current, LinkOption.NOFOLLOW_LINKS)
                    && Files.isSymbolicLink(current)) {
                throw new IOException("Generated file path contains a symbolic link: " + name);
            }
        }
        return path;
    }

    private static void markScriptsExecutable(Path root, Set<String> names) {
        if (!supportsPosix(root)) return;
        for (String name : names) {
            if (!name.startsWith("scripts/") && !"ci/verify".equals(name)) continue;
            try {
                Files.setPosixFilePermissions(root.resolve(name), EXECUTABLE);
            } catch (IOException failure) {
                throw new IllegalStateException("Could not set generated script permissions", failure);
            }
        }
    }

    private static boolean supportsPosix(Path root) {
        return root.getFileSystem().supportedFileAttributeViews().contains("posix");
    }

    private static Path safeRoot(Path project) throws IOException {
        if (project == null) throw new IOException("Project path is required");
        Path root = project.toAbsolutePath().normalize();
        Path fileName = root.getFileName();
        if (fileName == null || root.getParent() == null) {
            throw new IOException("Project path must name a specific directory");
        }
        if (Files.exists(root, LinkOption.NOFOLLOW_LINKS) && Files.isSymbolicLink(root)) {
            throw new IOException("Project directory must not be a symbolic link");
        }
        return root;
    }

    private static void requireEmptyOrMissing(Path root) throws IOException {
        if (!Files.exists(root, LinkOption.NOFOLLOW_LINKS)) return;
        if (!Files.isDirectory(root, LinkOption.NOFOLLOW_LINKS)) {
            throw new IOException("Project output exists and is not a directory");
        }
        try (var entries = Files.list(root)) {
            if (entries.findAny().isPresent()) {
                throw new IOException("Project output directory is not empty");
            }
        }
    }

    private static void requireBlueprintOnly(Path root) throws IOException {
        try (var entries = Files.list(root)) {
            List<Path> unexpected = entries
                    .filter(path -> !BLUEPRINT_FILE.equals(path.getFileName().toString()))
                    .limit(2)
                    .toList();
            if (!unexpected.isEmpty()) {
                throw new IOException("A blueprint without a lock can only be rendered in a "
                        + "directory containing appchain.yaml");
            }
        }
    }

    private static byte[] boundedFile(Path path, int maximum, String label) throws IOException {
        if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
            throw new IOException("Project " + label + " is missing");
        }
        if (Files.size(path) > maximum) {
            throw new IOException("Project " + label + " exceeds " + maximum + " bytes");
        }
        return Files.readAllBytes(path);
    }

    private static byte[] utf8(String value) {
        return value.getBytes(StandardCharsets.UTF_8);
    }

    private static <T> List<T> safeList(List<T> values) {
        return values == null ? List.of() : values;
    }

    private static <K, V> Map<K, V> safeMap(Map<K, V> values) {
        return values == null ? Map.of() : values;
    }

    private static ObjectMapper configured(ObjectMapper mapper) {
        return mapper.enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION)
                .enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS)
                .enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
    }

    private static void requireEqual(String label, Object expected, Object actual)
            throws IOException {
        if (!java.util.Objects.equals(expected, actual)) {
            throw new IOException("Project " + label + " does not match its blueprint/catalog");
        }
    }
}
