#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd -P)"
INSTANCE="${1:-master-demo}"
AUTO="${SHOWCASE_DEMO_AUTO:-false}"
pause() { [ "$AUTO" = true ] || { printf '\nPress Return to continue: %s\n' "$1"; read -r _; }; }

"$HERE/showcase.sh" doctor
pause "start the three-node light cluster and composite/anchor quickstart"
"$HERE/showcase.sh" quickstart --instance "$INSTANCE" --nodes 3
pause "inspect the resolved, redacted deployment configuration"
"$HERE/showcase.sh" config show --instance "$INSTANCE"
"$HERE/showcase.sh" config paths --instance "$INSTANCE"
pause "exercise every lightweight stock scenario"
"$HERE/showcase.sh" run orders --instance "$INSTANCE"
"$HERE/showcase.sh" run registry --instance "$INSTANCE"
"$HERE/showcase.sh" run approvals --instance "$INSTANCE"
"$HERE/showcase.sh" run balances --instance "$INSTANCE"
"$HERE/showcase.sh" run documents --instance "$INSTANCE"
"$HERE/showcase.sh" run composite --instance "$INSTANCE"
"$HERE/showcase.sh" run roles --instance "$INSTANCE"
"$HERE/showcase.sh" run eutxo --instance "$INSTANCE"
pause "add governed node 3 to the live three-node bootstrap cluster"
"$HERE/showcase.sh" member join 3 --instance "$INSTANCE"
"$HERE/showcase.sh" config show --instance "$INSTANCE"
pause "advance valid state-machine traffic and activate node 3 on every chain"
"$HERE/showcase.sh" governance activate --instance "$INSTANCE"
"$HERE/showcase.sh" config show --instance "$INSTANCE"
pause "schedule MPF finality from 2-of-4 to 3-of-4"
"$HERE/showcase.sh" threshold set 3 --instance "$INSTANCE"
"$HERE/showcase.sh" config show --instance "$INSTANCE"
pause "activate 3-of-4 and finalize a proof block on every chain"
"$HERE/showcase.sh" governance activate --instance "$INSTANCE"
"$HERE/showcase.sh" config show --instance "$INSTANCE"
"$HERE/showcase.sh" verify all --instance "$INSTANCE"
pause "restart retained state and the governed joiner"
"$HERE/showcase.sh" restart --instance "$INSTANCE"
"$HERE/showcase.sh" verify all --instance "$INSTANCE"
"$HERE/showcase.sh" ui --instance "$INSTANCE"
printf '\nDemo complete. Stop without deleting data:\n  ./showcase.sh stop --instance %s\n' "$INSTANCE"
